// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               v6.33.4
// source: game.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "game";

export enum Suit {
  SUIT_UNKNOWN = 0,
  SUIT_SOU = 1,
  SUIT_PIN = 2,
  SUIT_MAN = 3,
  SUIT_JIHAI = 4,
  UNRECOGNIZED = -1,
}

export function suitFromJSON(object: any): Suit {
  switch (object) {
    case 0:
    case "SUIT_UNKNOWN":
      return Suit.SUIT_UNKNOWN;
    case 1:
    case "SUIT_SOU":
      return Suit.SUIT_SOU;
    case 2:
    case "SUIT_PIN":
      return Suit.SUIT_PIN;
    case 3:
    case "SUIT_MAN":
      return Suit.SUIT_MAN;
    case 4:
    case "SUIT_JIHAI":
      return Suit.SUIT_JIHAI;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Suit.UNRECOGNIZED;
  }
}

export function suitToJSON(object: Suit): string {
  switch (object) {
    case Suit.SUIT_UNKNOWN:
      return "SUIT_UNKNOWN";
    case Suit.SUIT_SOU:
      return "SUIT_SOU";
    case Suit.SUIT_PIN:
      return "SUIT_PIN";
    case Suit.SUIT_MAN:
      return "SUIT_MAN";
    case Suit.SUIT_JIHAI:
      return "SUIT_JIHAI";
    case Suit.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum ActionType {
  ACTION_UNKNOWN = 0,
  /** ACTION_DRAW - Base Actions */
  ACTION_DRAW = 1,
  ACTION_DISCARD = 2,
  /** ACTION_CHII - Melds */
  ACTION_CHII = 3,
  /** ACTION_PON - triplet */
  ACTION_PON = 4,
  /** ACTION_KAN - quad */
  ACTION_KAN = 5,
  /** ACTION_TSUMO - Wins */
  ACTION_TSUMO = 6,
  /** ACTION_RON - steal win */
  ACTION_RON = 7,
  /** ACTION_PASS - Others */
  ACTION_PASS = 8,
  /** ACTION_FLOWER_REVEAL - Fenghua rule: drawing and exposing a flower tile */
  ACTION_FLOWER_REVEAL = 9,
  UNRECOGNIZED = -1,
}

export function actionTypeFromJSON(object: any): ActionType {
  switch (object) {
    case 0:
    case "ACTION_UNKNOWN":
      return ActionType.ACTION_UNKNOWN;
    case 1:
    case "ACTION_DRAW":
      return ActionType.ACTION_DRAW;
    case 2:
    case "ACTION_DISCARD":
      return ActionType.ACTION_DISCARD;
    case 3:
    case "ACTION_CHII":
      return ActionType.ACTION_CHII;
    case 4:
    case "ACTION_PON":
      return ActionType.ACTION_PON;
    case 5:
    case "ACTION_KAN":
      return ActionType.ACTION_KAN;
    case 6:
    case "ACTION_TSUMO":
      return ActionType.ACTION_TSUMO;
    case 7:
    case "ACTION_RON":
      return ActionType.ACTION_RON;
    case 8:
    case "ACTION_PASS":
      return ActionType.ACTION_PASS;
    case 9:
    case "ACTION_FLOWER_REVEAL":
      return ActionType.ACTION_FLOWER_REVEAL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ActionType.UNRECOGNIZED;
  }
}

export function actionTypeToJSON(object: ActionType): string {
  switch (object) {
    case ActionType.ACTION_UNKNOWN:
      return "ACTION_UNKNOWN";
    case ActionType.ACTION_DRAW:
      return "ACTION_DRAW";
    case ActionType.ACTION_DISCARD:
      return "ACTION_DISCARD";
    case ActionType.ACTION_CHII:
      return "ACTION_CHII";
    case ActionType.ACTION_PON:
      return "ACTION_PON";
    case ActionType.ACTION_KAN:
      return "ACTION_KAN";
    case ActionType.ACTION_TSUMO:
      return "ACTION_TSUMO";
    case ActionType.ACTION_RON:
      return "ACTION_RON";
    case ActionType.ACTION_PASS:
      return "ACTION_PASS";
    case ActionType.ACTION_FLOWER_REVEAL:
      return "ACTION_FLOWER_REVEAL";
    case ActionType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum MeldDirection {
  MELD_DIRECTION_UNKNOWN = 0,
  MELD_DIRECTION_RIGHT = 1,
  MELD_DIRECTION_ACROSS = 2,
  MELD_DIRECTION_LEFT = 3,
  UNRECOGNIZED = -1,
}

export function meldDirectionFromJSON(object: any): MeldDirection {
  switch (object) {
    case 0:
    case "MELD_DIRECTION_UNKNOWN":
      return MeldDirection.MELD_DIRECTION_UNKNOWN;
    case 1:
    case "MELD_DIRECTION_RIGHT":
      return MeldDirection.MELD_DIRECTION_RIGHT;
    case 2:
    case "MELD_DIRECTION_ACROSS":
      return MeldDirection.MELD_DIRECTION_ACROSS;
    case 3:
    case "MELD_DIRECTION_LEFT":
      return MeldDirection.MELD_DIRECTION_LEFT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MeldDirection.UNRECOGNIZED;
  }
}

export function meldDirectionToJSON(object: MeldDirection): string {
  switch (object) {
    case MeldDirection.MELD_DIRECTION_UNKNOWN:
      return "MELD_DIRECTION_UNKNOWN";
    case MeldDirection.MELD_DIRECTION_RIGHT:
      return "MELD_DIRECTION_RIGHT";
    case MeldDirection.MELD_DIRECTION_ACROSS:
      return "MELD_DIRECTION_ACROSS";
    case MeldDirection.MELD_DIRECTION_LEFT:
      return "MELD_DIRECTION_LEFT";
    case MeldDirection.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum GamePhase {
  PHASE_INIT = 0,
  PHASE_DEAL = 1,
  /** PHASE_PLAYER_TURN - Waiting for them to discard */
  PHASE_PLAYER_TURN = 2,
  /** PHASE_WAIT_DISCARDS - Someone discarded, waiting a few sec for steals */
  PHASE_WAIT_DISCARDS = 3,
  PHASE_ROUND_END = 4,
  UNRECOGNIZED = -1,
}

export function gamePhaseFromJSON(object: any): GamePhase {
  switch (object) {
    case 0:
    case "PHASE_INIT":
      return GamePhase.PHASE_INIT;
    case 1:
    case "PHASE_DEAL":
      return GamePhase.PHASE_DEAL;
    case 2:
    case "PHASE_PLAYER_TURN":
      return GamePhase.PHASE_PLAYER_TURN;
    case 3:
    case "PHASE_WAIT_DISCARDS":
      return GamePhase.PHASE_WAIT_DISCARDS;
    case 4:
    case "PHASE_ROUND_END":
      return GamePhase.PHASE_ROUND_END;
    case -1:
    case "UNRECOGNIZED":
    default:
      return GamePhase.UNRECOGNIZED;
  }
}

export function gamePhaseToJSON(object: GamePhase): string {
  switch (object) {
    case GamePhase.PHASE_INIT:
      return "PHASE_INIT";
    case GamePhase.PHASE_DEAL:
      return "PHASE_DEAL";
    case GamePhase.PHASE_PLAYER_TURN:
      return "PHASE_PLAYER_TURN";
    case GamePhase.PHASE_WAIT_DISCARDS:
      return "PHASE_WAIT_DISCARDS";
    case GamePhase.PHASE_ROUND_END:
      return "PHASE_ROUND_END";
    case GamePhase.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Tile {
  /** Unique identifier for the tile (0-135). */
  id: number;
  suit: Suit;
  /**
   * For suits 1-3, value is 1-9. Wait! In mahjong it's 1-9 for sou/pin/man,
   * 1-7 for jihai (East, South, West, North, Haku, Hatsu, Chun).
   */
  value: number;
}

export interface PlayerAction {
  type: ActionType;
  /** The tile being acted upon (e.g. the tile being discarded or stolen). */
  tile:
    | Tile
    | undefined;
  /** The subset of hand tiles revealed to complete the action (e.g. 2 tiles for a Chow/Pong). */
  meldTiles: Tile[];
  /**
   * Which player is targeted (0-3).
   * (e.g. Who did we Ron from? Who did we Pong from?)
   */
  targetPlayer: number;
  /** Context flags for win evaluations */
  isRobbingKong: boolean;
  isBottomTile: boolean;
  isBloomingKong: boolean;
}

export interface Meld {
  type: ActionType;
  tiles: Tile[];
  /**
   * Relative direction of the player who discarded the called tile.
   * 1: Right (shimocha), 2: Across (toimen), 3: Left (kamicha).
   */
  calledDirection: MeldDirection;
  /** The ID of the specific tile that was called (useful for UI rendering to know which one to rotate sideways). */
  calledTileId: number;
}

export interface PlayerState {
  /** 0=East, 1=South, 2=West, 3=North */
  seat: number;
  /** Number of points the player has */
  score: number;
  /**
   * The tiles currently held in the closed hand.
   * In a broadcast to other players, this might be empty for security.
   */
  closedHand: Tile[];
  /** The number of tiles in the hand (always public). */
  handSize: number;
  /** Opened melds (Chows, Pongs, Kongs) */
  openMelds: Meld[];
  /** Discarded tiles pool */
  discards: Tile[];
  /** Track the player's specific seat wind (1: East, 2: South, 3: West, 4: North) */
  seatWind: number;
  /** Track the specific flower tiles the player has melded (IDs 136-143) */
  flowerMelds: Tile[];
  /** Kong bonus context flags (set by game loop before calling EvaluateHand) */
  hasBuddingDirectKong: boolean;
  hasBloomingDirectKong: boolean;
  hasBuddingClosedKong: boolean;
  hasBloomingClosedKong: boolean;
  hasBuddingRiskyKong: boolean;
  hasBloomingRiskyKong: boolean;
  hasBloomingFlowerKong: boolean;
}

export interface GameState {
  /** UUID for the match */
  matchId: string;
  phase: GamePhase;
  /** Who's turn is it right now? (0-3) */
  activePlayer: number;
  /** The 4 players. */
  players: PlayerState[];
  /** Number of tiles left in the wall */
  wallCount: number;
  /** Current hand number (e.g. East 1 = 1, East 2 = 2) */
  handNum: number;
  /** The current active discard (if in PHASE_WAIT_DISCARDS) */
  activeDiscard:
    | Tile
    | undefined;
  /** The current active wild tiles for this round */
  wildTiles: Tile[];
  /** The prevailing (round) wind for Fenghua Mahjong (1=East, 2=South, 3=West, 4=North) */
  prevailingWind: number;
  /** The base64-encoded MT19937 seed used to shuffle the wall (for replay verification) */
  wallSeed: string;
  /** Per-seat available interrupt actions during PHASE_WAIT_DISCARDS */
  availableActions: { [key: number]: ActionList };
}

export interface GameState_AvailableActionsEntry {
  key: number;
  value: ActionList | undefined;
}

/** A list of action types, used as the value type for the available_actions map. */
export interface ActionList {
  actions: ActionType[];
}

function createBaseTile(): Tile {
  return { id: 0, suit: 0, value: 0 };
}

export const Tile: MessageFns<Tile> = {
  encode(message: Tile, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).uint32(message.id);
    }
    if (message.suit !== 0) {
      writer.uint32(16).int32(message.suit);
    }
    if (message.value !== 0) {
      writer.uint32(24).uint32(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Tile {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTile();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.suit = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.value = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Tile {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      suit: isSet(object.suit) ? suitFromJSON(object.suit) : 0,
      value: isSet(object.value) ? globalThis.Number(object.value) : 0,
    };
  },

  toJSON(message: Tile): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.suit !== 0) {
      obj.suit = suitToJSON(message.suit);
    }
    if (message.value !== 0) {
      obj.value = Math.round(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Tile>, I>>(base?: I): Tile {
    return Tile.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Tile>, I>>(object: I): Tile {
    const message = createBaseTile();
    message.id = object.id ?? 0;
    message.suit = object.suit ?? 0;
    message.value = object.value ?? 0;
    return message;
  },
};

function createBasePlayerAction(): PlayerAction {
  return {
    type: 0,
    tile: undefined,
    meldTiles: [],
    targetPlayer: 0,
    isRobbingKong: false,
    isBottomTile: false,
    isBloomingKong: false,
  };
}

export const PlayerAction: MessageFns<PlayerAction> = {
  encode(message: PlayerAction, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    if (message.tile !== undefined) {
      Tile.encode(message.tile, writer.uint32(18).fork()).join();
    }
    for (const v of message.meldTiles) {
      Tile.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.targetPlayer !== 0) {
      writer.uint32(32).uint32(message.targetPlayer);
    }
    if (message.isRobbingKong !== false) {
      writer.uint32(40).bool(message.isRobbingKong);
    }
    if (message.isBottomTile !== false) {
      writer.uint32(48).bool(message.isBottomTile);
    }
    if (message.isBloomingKong !== false) {
      writer.uint32(56).bool(message.isBloomingKong);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerAction {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerAction();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tile = Tile.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.meldTiles.push(Tile.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.targetPlayer = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isRobbingKong = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isBottomTile = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isBloomingKong = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerAction {
    return {
      type: isSet(object.type) ? actionTypeFromJSON(object.type) : 0,
      tile: isSet(object.tile) ? Tile.fromJSON(object.tile) : undefined,
      meldTiles: globalThis.Array.isArray(object?.meldTiles)
        ? object.meldTiles.map((e: any) => Tile.fromJSON(e))
        : globalThis.Array.isArray(object?.meld_tiles)
        ? object.meld_tiles.map((e: any) => Tile.fromJSON(e))
        : [],
      targetPlayer: isSet(object.targetPlayer)
        ? globalThis.Number(object.targetPlayer)
        : isSet(object.target_player)
        ? globalThis.Number(object.target_player)
        : 0,
      isRobbingKong: isSet(object.isRobbingKong)
        ? globalThis.Boolean(object.isRobbingKong)
        : isSet(object.is_robbing_kong)
        ? globalThis.Boolean(object.is_robbing_kong)
        : false,
      isBottomTile: isSet(object.isBottomTile)
        ? globalThis.Boolean(object.isBottomTile)
        : isSet(object.is_bottom_tile)
        ? globalThis.Boolean(object.is_bottom_tile)
        : false,
      isBloomingKong: isSet(object.isBloomingKong)
        ? globalThis.Boolean(object.isBloomingKong)
        : isSet(object.is_blooming_kong)
        ? globalThis.Boolean(object.is_blooming_kong)
        : false,
    };
  },

  toJSON(message: PlayerAction): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = actionTypeToJSON(message.type);
    }
    if (message.tile !== undefined) {
      obj.tile = Tile.toJSON(message.tile);
    }
    if (message.meldTiles?.length) {
      obj.meldTiles = message.meldTiles.map((e) => Tile.toJSON(e));
    }
    if (message.targetPlayer !== 0) {
      obj.targetPlayer = Math.round(message.targetPlayer);
    }
    if (message.isRobbingKong !== false) {
      obj.isRobbingKong = message.isRobbingKong;
    }
    if (message.isBottomTile !== false) {
      obj.isBottomTile = message.isBottomTile;
    }
    if (message.isBloomingKong !== false) {
      obj.isBloomingKong = message.isBloomingKong;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerAction>, I>>(base?: I): PlayerAction {
    return PlayerAction.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerAction>, I>>(object: I): PlayerAction {
    const message = createBasePlayerAction();
    message.type = object.type ?? 0;
    message.tile = (object.tile !== undefined && object.tile !== null) ? Tile.fromPartial(object.tile) : undefined;
    message.meldTiles = object.meldTiles?.map((e) => Tile.fromPartial(e)) || [];
    message.targetPlayer = object.targetPlayer ?? 0;
    message.isRobbingKong = object.isRobbingKong ?? false;
    message.isBottomTile = object.isBottomTile ?? false;
    message.isBloomingKong = object.isBloomingKong ?? false;
    return message;
  },
};

function createBaseMeld(): Meld {
  return { type: 0, tiles: [], calledDirection: 0, calledTileId: 0 };
}

export const Meld: MessageFns<Meld> = {
  encode(message: Meld, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== 0) {
      writer.uint32(8).int32(message.type);
    }
    for (const v of message.tiles) {
      Tile.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.calledDirection !== 0) {
      writer.uint32(24).int32(message.calledDirection);
    }
    if (message.calledTileId !== 0) {
      writer.uint32(32).uint32(message.calledTileId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Meld {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMeld();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tiles.push(Tile.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.calledDirection = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.calledTileId = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Meld {
    return {
      type: isSet(object.type) ? actionTypeFromJSON(object.type) : 0,
      tiles: globalThis.Array.isArray(object?.tiles) ? object.tiles.map((e: any) => Tile.fromJSON(e)) : [],
      calledDirection: isSet(object.calledDirection)
        ? meldDirectionFromJSON(object.calledDirection)
        : isSet(object.called_direction)
        ? meldDirectionFromJSON(object.called_direction)
        : 0,
      calledTileId: isSet(object.calledTileId)
        ? globalThis.Number(object.calledTileId)
        : isSet(object.called_tile_id)
        ? globalThis.Number(object.called_tile_id)
        : 0,
    };
  },

  toJSON(message: Meld): unknown {
    const obj: any = {};
    if (message.type !== 0) {
      obj.type = actionTypeToJSON(message.type);
    }
    if (message.tiles?.length) {
      obj.tiles = message.tiles.map((e) => Tile.toJSON(e));
    }
    if (message.calledDirection !== 0) {
      obj.calledDirection = meldDirectionToJSON(message.calledDirection);
    }
    if (message.calledTileId !== 0) {
      obj.calledTileId = Math.round(message.calledTileId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Meld>, I>>(base?: I): Meld {
    return Meld.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Meld>, I>>(object: I): Meld {
    const message = createBaseMeld();
    message.type = object.type ?? 0;
    message.tiles = object.tiles?.map((e) => Tile.fromPartial(e)) || [];
    message.calledDirection = object.calledDirection ?? 0;
    message.calledTileId = object.calledTileId ?? 0;
    return message;
  },
};

function createBasePlayerState(): PlayerState {
  return {
    seat: 0,
    score: 0,
    closedHand: [],
    handSize: 0,
    openMelds: [],
    discards: [],
    seatWind: 0,
    flowerMelds: [],
    hasBuddingDirectKong: false,
    hasBloomingDirectKong: false,
    hasBuddingClosedKong: false,
    hasBloomingClosedKong: false,
    hasBuddingRiskyKong: false,
    hasBloomingRiskyKong: false,
    hasBloomingFlowerKong: false,
  };
}

export const PlayerState: MessageFns<PlayerState> = {
  encode(message: PlayerState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.seat !== 0) {
      writer.uint32(8).uint32(message.seat);
    }
    if (message.score !== 0) {
      writer.uint32(16).int32(message.score);
    }
    for (const v of message.closedHand) {
      Tile.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.handSize !== 0) {
      writer.uint32(32).uint32(message.handSize);
    }
    for (const v of message.openMelds) {
      Meld.encode(v!, writer.uint32(42).fork()).join();
    }
    for (const v of message.discards) {
      Tile.encode(v!, writer.uint32(50).fork()).join();
    }
    if (message.seatWind !== 0) {
      writer.uint32(56).uint32(message.seatWind);
    }
    for (const v of message.flowerMelds) {
      Tile.encode(v!, writer.uint32(66).fork()).join();
    }
    if (message.hasBuddingDirectKong !== false) {
      writer.uint32(72).bool(message.hasBuddingDirectKong);
    }
    if (message.hasBloomingDirectKong !== false) {
      writer.uint32(80).bool(message.hasBloomingDirectKong);
    }
    if (message.hasBuddingClosedKong !== false) {
      writer.uint32(88).bool(message.hasBuddingClosedKong);
    }
    if (message.hasBloomingClosedKong !== false) {
      writer.uint32(96).bool(message.hasBloomingClosedKong);
    }
    if (message.hasBuddingRiskyKong !== false) {
      writer.uint32(104).bool(message.hasBuddingRiskyKong);
    }
    if (message.hasBloomingRiskyKong !== false) {
      writer.uint32(112).bool(message.hasBloomingRiskyKong);
    }
    if (message.hasBloomingFlowerKong !== false) {
      writer.uint32(120).bool(message.hasBloomingFlowerKong);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PlayerState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePlayerState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.seat = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.score = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.closedHand.push(Tile.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.handSize = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.openMelds.push(Meld.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.discards.push(Tile.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.seatWind = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.flowerMelds.push(Tile.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.hasBuddingDirectKong = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.hasBloomingDirectKong = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.hasBuddingClosedKong = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.hasBloomingClosedKong = reader.bool();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.hasBuddingRiskyKong = reader.bool();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.hasBloomingRiskyKong = reader.bool();
          continue;
        }
        case 15: {
          if (tag !== 120) {
            break;
          }

          message.hasBloomingFlowerKong = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PlayerState {
    return {
      seat: isSet(object.seat) ? globalThis.Number(object.seat) : 0,
      score: isSet(object.score) ? globalThis.Number(object.score) : 0,
      closedHand: globalThis.Array.isArray(object?.closedHand)
        ? object.closedHand.map((e: any) => Tile.fromJSON(e))
        : globalThis.Array.isArray(object?.closed_hand)
        ? object.closed_hand.map((e: any) => Tile.fromJSON(e))
        : [],
      handSize: isSet(object.handSize)
        ? globalThis.Number(object.handSize)
        : isSet(object.hand_size)
        ? globalThis.Number(object.hand_size)
        : 0,
      openMelds: globalThis.Array.isArray(object?.openMelds)
        ? object.openMelds.map((e: any) => Meld.fromJSON(e))
        : globalThis.Array.isArray(object?.open_melds)
        ? object.open_melds.map((e: any) => Meld.fromJSON(e))
        : [],
      discards: globalThis.Array.isArray(object?.discards) ? object.discards.map((e: any) => Tile.fromJSON(e)) : [],
      seatWind: isSet(object.seatWind)
        ? globalThis.Number(object.seatWind)
        : isSet(object.seat_wind)
        ? globalThis.Number(object.seat_wind)
        : 0,
      flowerMelds: globalThis.Array.isArray(object?.flowerMelds)
        ? object.flowerMelds.map((e: any) => Tile.fromJSON(e))
        : globalThis.Array.isArray(object?.flower_melds)
        ? object.flower_melds.map((e: any) => Tile.fromJSON(e))
        : [],
      hasBuddingDirectKong: isSet(object.hasBuddingDirectKong)
        ? globalThis.Boolean(object.hasBuddingDirectKong)
        : isSet(object.has_budding_direct_kong)
        ? globalThis.Boolean(object.has_budding_direct_kong)
        : false,
      hasBloomingDirectKong: isSet(object.hasBloomingDirectKong)
        ? globalThis.Boolean(object.hasBloomingDirectKong)
        : isSet(object.has_blooming_direct_kong)
        ? globalThis.Boolean(object.has_blooming_direct_kong)
        : false,
      hasBuddingClosedKong: isSet(object.hasBuddingClosedKong)
        ? globalThis.Boolean(object.hasBuddingClosedKong)
        : isSet(object.has_budding_closed_kong)
        ? globalThis.Boolean(object.has_budding_closed_kong)
        : false,
      hasBloomingClosedKong: isSet(object.hasBloomingClosedKong)
        ? globalThis.Boolean(object.hasBloomingClosedKong)
        : isSet(object.has_blooming_closed_kong)
        ? globalThis.Boolean(object.has_blooming_closed_kong)
        : false,
      hasBuddingRiskyKong: isSet(object.hasBuddingRiskyKong)
        ? globalThis.Boolean(object.hasBuddingRiskyKong)
        : isSet(object.has_budding_risky_kong)
        ? globalThis.Boolean(object.has_budding_risky_kong)
        : false,
      hasBloomingRiskyKong: isSet(object.hasBloomingRiskyKong)
        ? globalThis.Boolean(object.hasBloomingRiskyKong)
        : isSet(object.has_blooming_risky_kong)
        ? globalThis.Boolean(object.has_blooming_risky_kong)
        : false,
      hasBloomingFlowerKong: isSet(object.hasBloomingFlowerKong)
        ? globalThis.Boolean(object.hasBloomingFlowerKong)
        : isSet(object.has_blooming_flower_kong)
        ? globalThis.Boolean(object.has_blooming_flower_kong)
        : false,
    };
  },

  toJSON(message: PlayerState): unknown {
    const obj: any = {};
    if (message.seat !== 0) {
      obj.seat = Math.round(message.seat);
    }
    if (message.score !== 0) {
      obj.score = Math.round(message.score);
    }
    if (message.closedHand?.length) {
      obj.closedHand = message.closedHand.map((e) => Tile.toJSON(e));
    }
    if (message.handSize !== 0) {
      obj.handSize = Math.round(message.handSize);
    }
    if (message.openMelds?.length) {
      obj.openMelds = message.openMelds.map((e) => Meld.toJSON(e));
    }
    if (message.discards?.length) {
      obj.discards = message.discards.map((e) => Tile.toJSON(e));
    }
    if (message.seatWind !== 0) {
      obj.seatWind = Math.round(message.seatWind);
    }
    if (message.flowerMelds?.length) {
      obj.flowerMelds = message.flowerMelds.map((e) => Tile.toJSON(e));
    }
    if (message.hasBuddingDirectKong !== false) {
      obj.hasBuddingDirectKong = message.hasBuddingDirectKong;
    }
    if (message.hasBloomingDirectKong !== false) {
      obj.hasBloomingDirectKong = message.hasBloomingDirectKong;
    }
    if (message.hasBuddingClosedKong !== false) {
      obj.hasBuddingClosedKong = message.hasBuddingClosedKong;
    }
    if (message.hasBloomingClosedKong !== false) {
      obj.hasBloomingClosedKong = message.hasBloomingClosedKong;
    }
    if (message.hasBuddingRiskyKong !== false) {
      obj.hasBuddingRiskyKong = message.hasBuddingRiskyKong;
    }
    if (message.hasBloomingRiskyKong !== false) {
      obj.hasBloomingRiskyKong = message.hasBloomingRiskyKong;
    }
    if (message.hasBloomingFlowerKong !== false) {
      obj.hasBloomingFlowerKong = message.hasBloomingFlowerKong;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PlayerState>, I>>(base?: I): PlayerState {
    return PlayerState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PlayerState>, I>>(object: I): PlayerState {
    const message = createBasePlayerState();
    message.seat = object.seat ?? 0;
    message.score = object.score ?? 0;
    message.closedHand = object.closedHand?.map((e) => Tile.fromPartial(e)) || [];
    message.handSize = object.handSize ?? 0;
    message.openMelds = object.openMelds?.map((e) => Meld.fromPartial(e)) || [];
    message.discards = object.discards?.map((e) => Tile.fromPartial(e)) || [];
    message.seatWind = object.seatWind ?? 0;
    message.flowerMelds = object.flowerMelds?.map((e) => Tile.fromPartial(e)) || [];
    message.hasBuddingDirectKong = object.hasBuddingDirectKong ?? false;
    message.hasBloomingDirectKong = object.hasBloomingDirectKong ?? false;
    message.hasBuddingClosedKong = object.hasBuddingClosedKong ?? false;
    message.hasBloomingClosedKong = object.hasBloomingClosedKong ?? false;
    message.hasBuddingRiskyKong = object.hasBuddingRiskyKong ?? false;
    message.hasBloomingRiskyKong = object.hasBloomingRiskyKong ?? false;
    message.hasBloomingFlowerKong = object.hasBloomingFlowerKong ?? false;
    return message;
  },
};

function createBaseGameState(): GameState {
  return {
    matchId: "",
    phase: 0,
    activePlayer: 0,
    players: [],
    wallCount: 0,
    handNum: 0,
    activeDiscard: undefined,
    wildTiles: [],
    prevailingWind: 0,
    wallSeed: "",
    availableActions: {},
  };
}

export const GameState: MessageFns<GameState> = {
  encode(message: GameState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.matchId !== "") {
      writer.uint32(10).string(message.matchId);
    }
    if (message.phase !== 0) {
      writer.uint32(16).int32(message.phase);
    }
    if (message.activePlayer !== 0) {
      writer.uint32(24).uint32(message.activePlayer);
    }
    for (const v of message.players) {
      PlayerState.encode(v!, writer.uint32(34).fork()).join();
    }
    if (message.wallCount !== 0) {
      writer.uint32(40).uint32(message.wallCount);
    }
    if (message.handNum !== 0) {
      writer.uint32(48).uint32(message.handNum);
    }
    if (message.activeDiscard !== undefined) {
      Tile.encode(message.activeDiscard, writer.uint32(58).fork()).join();
    }
    for (const v of message.wildTiles) {
      Tile.encode(v!, writer.uint32(66).fork()).join();
    }
    if (message.prevailingWind !== 0) {
      writer.uint32(88).uint32(message.prevailingWind);
    }
    if (message.wallSeed !== "") {
      writer.uint32(98).string(message.wallSeed);
    }
    globalThis.Object.entries(message.availableActions).forEach(([key, value]: [string, ActionList]) => {
      GameState_AvailableActionsEntry.encode({ key: key as any, value }, writer.uint32(106).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GameState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGameState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.matchId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.phase = reader.int32() as any;
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.activePlayer = reader.uint32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.players.push(PlayerState.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.wallCount = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.handNum = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.activeDiscard = Tile.decode(reader, reader.uint32());
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.wildTiles.push(Tile.decode(reader, reader.uint32()));
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.prevailingWind = reader.uint32();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.wallSeed = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          const entry13 = GameState_AvailableActionsEntry.decode(reader, reader.uint32());
          if (entry13.value !== undefined) {
            message.availableActions[entry13.key] = entry13.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GameState {
    return {
      matchId: isSet(object.matchId)
        ? globalThis.String(object.matchId)
        : isSet(object.match_id)
        ? globalThis.String(object.match_id)
        : "",
      phase: isSet(object.phase) ? gamePhaseFromJSON(object.phase) : 0,
      activePlayer: isSet(object.activePlayer)
        ? globalThis.Number(object.activePlayer)
        : isSet(object.active_player)
        ? globalThis.Number(object.active_player)
        : 0,
      players: globalThis.Array.isArray(object?.players) ? object.players.map((e: any) => PlayerState.fromJSON(e)) : [],
      wallCount: isSet(object.wallCount)
        ? globalThis.Number(object.wallCount)
        : isSet(object.wall_count)
        ? globalThis.Number(object.wall_count)
        : 0,
      handNum: isSet(object.handNum)
        ? globalThis.Number(object.handNum)
        : isSet(object.hand_num)
        ? globalThis.Number(object.hand_num)
        : 0,
      activeDiscard: isSet(object.activeDiscard)
        ? Tile.fromJSON(object.activeDiscard)
        : isSet(object.active_discard)
        ? Tile.fromJSON(object.active_discard)
        : undefined,
      wildTiles: globalThis.Array.isArray(object?.wildTiles)
        ? object.wildTiles.map((e: any) => Tile.fromJSON(e))
        : globalThis.Array.isArray(object?.wild_tiles)
        ? object.wild_tiles.map((e: any) => Tile.fromJSON(e))
        : [],
      prevailingWind: isSet(object.prevailingWind)
        ? globalThis.Number(object.prevailingWind)
        : isSet(object.prevailing_wind)
        ? globalThis.Number(object.prevailing_wind)
        : 0,
      wallSeed: isSet(object.wallSeed)
        ? globalThis.String(object.wallSeed)
        : isSet(object.wall_seed)
        ? globalThis.String(object.wall_seed)
        : "",
      availableActions: isObject(object.availableActions)
        ? (globalThis.Object.entries(object.availableActions) as [string, any][]).reduce(
          (acc: { [key: number]: ActionList }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = ActionList.fromJSON(value);
            return acc;
          },
          {},
        )
        : isObject(object.available_actions)
        ? (globalThis.Object.entries(object.available_actions) as [string, any][]).reduce(
          (acc: { [key: number]: ActionList }, [key, value]: [string, any]) => {
            acc[globalThis.Number(key)] = ActionList.fromJSON(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: GameState): unknown {
    const obj: any = {};
    if (message.matchId !== "") {
      obj.matchId = message.matchId;
    }
    if (message.phase !== 0) {
      obj.phase = gamePhaseToJSON(message.phase);
    }
    if (message.activePlayer !== 0) {
      obj.activePlayer = Math.round(message.activePlayer);
    }
    if (message.players?.length) {
      obj.players = message.players.map((e) => PlayerState.toJSON(e));
    }
    if (message.wallCount !== 0) {
      obj.wallCount = Math.round(message.wallCount);
    }
    if (message.handNum !== 0) {
      obj.handNum = Math.round(message.handNum);
    }
    if (message.activeDiscard !== undefined) {
      obj.activeDiscard = Tile.toJSON(message.activeDiscard);
    }
    if (message.wildTiles?.length) {
      obj.wildTiles = message.wildTiles.map((e) => Tile.toJSON(e));
    }
    if (message.prevailingWind !== 0) {
      obj.prevailingWind = Math.round(message.prevailingWind);
    }
    if (message.wallSeed !== "") {
      obj.wallSeed = message.wallSeed;
    }
    if (message.availableActions) {
      const entries = globalThis.Object.entries(message.availableActions) as [string, ActionList][];
      if (entries.length > 0) {
        obj.availableActions = {};
        entries.forEach(([k, v]) => {
          obj.availableActions[k] = ActionList.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GameState>, I>>(base?: I): GameState {
    return GameState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GameState>, I>>(object: I): GameState {
    const message = createBaseGameState();
    message.matchId = object.matchId ?? "";
    message.phase = object.phase ?? 0;
    message.activePlayer = object.activePlayer ?? 0;
    message.players = object.players?.map((e) => PlayerState.fromPartial(e)) || [];
    message.wallCount = object.wallCount ?? 0;
    message.handNum = object.handNum ?? 0;
    message.activeDiscard = (object.activeDiscard !== undefined && object.activeDiscard !== null)
      ? Tile.fromPartial(object.activeDiscard)
      : undefined;
    message.wildTiles = object.wildTiles?.map((e) => Tile.fromPartial(e)) || [];
    message.prevailingWind = object.prevailingWind ?? 0;
    message.wallSeed = object.wallSeed ?? "";
    message.availableActions = (globalThis.Object.entries(object.availableActions ?? {}) as [string, ActionList][])
      .reduce((acc: { [key: number]: ActionList }, [key, value]: [string, ActionList]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = ActionList.fromPartial(value);
        }
        return acc;
      }, {});
    return message;
  },
};

function createBaseGameState_AvailableActionsEntry(): GameState_AvailableActionsEntry {
  return { key: 0, value: undefined };
}

export const GameState_AvailableActionsEntry: MessageFns<GameState_AvailableActionsEntry> = {
  encode(message: GameState_AvailableActionsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).uint32(message.key);
    }
    if (message.value !== undefined) {
      ActionList.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GameState_AvailableActionsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGameState_AvailableActionsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = ActionList.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GameState_AvailableActionsEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? ActionList.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: GameState_AvailableActionsEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = ActionList.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GameState_AvailableActionsEntry>, I>>(base?: I): GameState_AvailableActionsEntry {
    return GameState_AvailableActionsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GameState_AvailableActionsEntry>, I>>(
    object: I,
  ): GameState_AvailableActionsEntry {
    const message = createBaseGameState_AvailableActionsEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? ActionList.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseActionList(): ActionList {
  return { actions: [] };
}

export const ActionList: MessageFns<ActionList> = {
  encode(message: ActionList, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.actions) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ActionList {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseActionList();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.actions.push(reader.int32() as any);

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.actions.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ActionList {
    return {
      actions: globalThis.Array.isArray(object?.actions) ? object.actions.map((e: any) => actionTypeFromJSON(e)) : [],
    };
  },

  toJSON(message: ActionList): unknown {
    const obj: any = {};
    if (message.actions?.length) {
      obj.actions = message.actions.map((e) => actionTypeToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ActionList>, I>>(base?: I): ActionList {
    return ActionList.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ActionList>, I>>(object: I): ActionList {
    const message = createBaseActionList();
    message.actions = object.actions?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
