package storage

import (
	"crypto/rand"
	"fmt"
	"math/big"
	"time"

	"gorm.io/gorm"
)

// User represents a player account. Email is the login identity; Username is a
// (non-unique) display name shown at the table.
type User struct {
	ID           uint      `gorm:"primaryKey;autoIncrement:false" json:"id"` // random sparse id, app-generated
	Email        string    `gorm:"uniqueIndex;not null;size:255" json:"email"`
	Username     string    `gorm:"not null;size:255" json:"username"` // display name (no longer unique)
	PasswordHash string    `gorm:"not null" json:"-"`
	Rating       int       `gorm:"default:1500" json:"rating"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`

	Matches []MatchPlayer `gorm:"foreignKey:UserID" json:"-"`
}

const (
	userIDMin  = 10000
	userIDSpan = 90000 // 99999 - 10000 + 1
)

// generateUserID returns a cryptographically-random id in [10000, 99999]. The
// range is kept well under 2^53 so the id round-trips exactly through the JWT
// `sub` claim, which is decoded as a float64.
func generateUserID() (uint, error) {
	n, err := rand.Int(rand.Reader, big.NewInt(userIDSpan))
	if err != nil {
		return 0, err
	}
	return uint(n.Int64()) + userIDMin, nil
}

// BeforeCreate assigns a random sparse id when one isn't already set, so users
// get non-sequential, unguessable ids instead of an auto-increment sequence.
func (u *User) BeforeCreate(tx *gorm.DB) error {
	if u.ID == 0 {
		id, err := generateUserID()
		if err != nil {
			return err
		}
		u.ID = id
	}
	return nil
}

// Match represents a single game of Mahjong
type Match struct {
	ID        string     `gorm:"type:uuid;primaryKey" json:"id"`                       // Generated by Go UUID
	Status    string     `gorm:"size:50;not null;default:'in_progress'" json:"status"` // in_progress, completed, aborted
	StartTime time.Time  `gorm:"not null" json:"startTime"`
	EndTime   *time.Time `json:"endTime,omitempty"`

	// Important Fenghua Settings
	Ruleset   string `gorm:"size:100;not null;default:'fenghua'" json:"ruleset"`
	WallSeed  string `gorm:"type:text" json:"wallSeed,omitempty"` // For verifying replays
	ReplayURL string `gorm:"type:text" json:"replayUrl,omitempty"`
	PaipuJSON string `gorm:"type:text" json:"paipuJson,omitempty"`

	// Relationships
	Players []MatchPlayer `gorm:"foreignKey:MatchID" json:"players"`
}

// MatchPlayer is the join table recording a user's performance in a specific match
type MatchPlayer struct {
	ID      uint   `gorm:"primaryKey" json:"-"`
	MatchID string `gorm:"type:uuid;index;not null" json:"matchId"`
	UserID  uint   `gorm:"index;not null" json:"userId"`

	Seat        uint  `gorm:"not null" json:"seat"` // 0=East, 1=South, 2=West, 3=North
	FinalScore  int32 `gorm:"not null;default:0" json:"finalScore"`
	Placement   uint  `gorm:"not null;default:0" json:"placement"` // 1st, 2nd, 3rd, 4th
	RatingDelta int   `gorm:"not null;default:0" json:"ratingDelta"`

	// Eager-loaded user info for match history API
	User User `gorm:"foreignKey:UserID" json:"user,omitempty"`
}

// PaipuRecord stores a per-round paipu replay
type PaipuRecord struct {
	ID        string    `gorm:"primaryKey;size:255" json:"id"` // matchID-handNum
	Data      string    `gorm:"type:text;not null" json:"data"`
	CreatedAt time.Time `json:"createdAt"`
}

// MatchReview caches one champion's review report for a match. A new champion
// (different CheckpointID) re-reviews without destroying the old report.
type MatchReview struct {
	ID           uint      `gorm:"primaryKey" json:"-"`
	MatchID      string    `gorm:"size:255;not null;uniqueIndex:idx_match_reviews_match_ckpt,priority:1;index" json:"matchId"`
	CheckpointID string    `gorm:"size:512;not null;uniqueIndex:idx_match_reviews_match_ckpt,priority:2" json:"checkpointId"`
	ReportJSON   string    `gorm:"type:text;not null" json:"-"`
	CreatedAt    time.Time `json:"createdAt"`
}

// AutoMigrate brings the schema up to date and safely transitions a legacy
// username-based users table to the email-based schema.
//
// The legacy schema is detected as a `users` table that has no `email` column.
// If such a table still holds rows we FAIL CLOSED with a diagnostic, because the
// email-based model has no backfill path and migrating must never silently
// destroy or half-migrate accounts. An empty legacy table is migrated in place.
// Finally, any stale unique index on `username` (left by the old schema) is
// dropped so display names are non-unique as designed. This runs at startup, so
// a failure surfaces immediately instead of depending on an out-of-band manual
// step executed at the right moment.
func AutoMigrate(db *gorm.DB) error {
	m := db.Migrator()

	if m.HasTable(&User{}) && !m.HasColumn(&User{}, "email") {
		var count int64
		if err := db.Table("users").Count(&count).Error; err != nil {
			return fmt.Errorf("inspecting legacy users table: %w", err)
		}
		if count > 0 {
			return fmt.Errorf("refusing to migrate: legacy %q table has %d row(s) and no email column; "+
				"the email-based schema has no backfill path — migrate or remove that data, then restart", "users", count)
		}
		// Empty legacy table: AutoMigrate below adds the email column in place.
	}

	if err := db.AutoMigrate(
		&User{},
		&Match{},
		&MatchPlayer{},
		&PaipuRecord{},
		&MatchReview{},
	); err != nil {
		return err
	}

	// Drop the stale unique index on username left by the old schema so display
	// names can repeat (the new model intentionally has no uniqueIndex on it).
	if m.HasIndex(&User{}, "idx_users_username") {
		if err := m.DropIndex(&User{}, "idx_users_username"); err != nil {
			return fmt.Errorf("dropping stale unique username index: %w", err)
		}
	}

	// Backfill the legacy ruleset key: "hometown" was renamed to "fenghua" in
	// 2026-06. Idempotent — only touches rows that still hold the old value.
	if err := db.Model(&Match{}).Where("ruleset = ?", "hometown").Update("ruleset", "fenghua").Error; err != nil {
		return fmt.Errorf("backfilling legacy ruleset key: %w", err)
	}
	return nil
}
