package storage

import (
	"crypto/rand"
	"math/big"
	"time"

	"gorm.io/gorm"
)

// User represents a player account. Email is the login identity; Username is a
// (non-unique) display name shown at the table.
type User struct {
	ID           uint      `gorm:"primaryKey;autoIncrement:false" json:"id"` // random sparse id, app-generated
	Email        string    `gorm:"uniqueIndex;not null;size:255" json:"email"`
	Username     string    `gorm:"not null;size:255" json:"username"` // display name (no longer unique)
	PasswordHash string    `gorm:"not null" json:"-"`
	Rating       int       `gorm:"default:1500" json:"rating"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`

	Matches []MatchPlayer `gorm:"foreignKey:UserID" json:"-"`
}

const (
	userIDMin  = 10000
	userIDSpan = 90000 // 99999 - 10000 + 1
)

// generateUserID returns a cryptographically-random id in [10000, 99999]. The
// range is kept well under 2^53 so the id round-trips exactly through the JWT
// `sub` claim, which is decoded as a float64.
func generateUserID() (uint, error) {
	n, err := rand.Int(rand.Reader, big.NewInt(userIDSpan))
	if err != nil {
		return 0, err
	}
	return uint(n.Int64()) + userIDMin, nil
}

// BeforeCreate assigns a random sparse id when one isn't already set, so users
// get non-sequential, unguessable ids instead of an auto-increment sequence.
func (u *User) BeforeCreate(tx *gorm.DB) error {
	if u.ID == 0 {
		id, err := generateUserID()
		if err != nil {
			return err
		}
		u.ID = id
	}
	return nil
}

// Match represents a single game of Mahjong
type Match struct {
	ID        string     `gorm:"type:uuid;primaryKey" json:"id"`                       // Generated by Go UUID
	Status    string     `gorm:"size:50;not null;default:'in_progress'" json:"status"` // in_progress, completed, aborted
	StartTime time.Time  `gorm:"not null" json:"startTime"`
	EndTime   *time.Time `json:"endTime,omitempty"`

	// Important Fenghua Settings
	Ruleset   string `gorm:"size:100;not null;default:'hometown'" json:"ruleset"`
	WallSeed  string `gorm:"type:text" json:"wallSeed,omitempty"` // For verifying replays
	ReplayURL string `gorm:"type:text" json:"replayUrl,omitempty"`
	PaipuJSON string `gorm:"type:text" json:"paipuJson,omitempty"`

	// Relationships
	Players []MatchPlayer `gorm:"foreignKey:MatchID" json:"players"`
}

// MatchPlayer is the join table recording a user's performance in a specific match
type MatchPlayer struct {
	ID      uint   `gorm:"primaryKey" json:"-"`
	MatchID string `gorm:"type:uuid;index;not null" json:"matchId"`
	UserID  uint   `gorm:"index;not null" json:"userId"`

	Seat        uint  `gorm:"not null" json:"seat"` // 0=East, 1=South, 2=West, 3=North
	FinalScore  int32 `gorm:"not null;default:0" json:"finalScore"`
	Placement   uint  `gorm:"not null;default:0" json:"placement"` // 1st, 2nd, 3rd, 4th
	RatingDelta int   `gorm:"not null;default:0" json:"ratingDelta"`

	// Eager-loaded user info for match history API
	User User `gorm:"foreignKey:UserID" json:"user,omitempty"`
}

// PaipuRecord stores a per-round paipu replay
type PaipuRecord struct {
	ID        string    `gorm:"primaryKey;size:255" json:"id"` // matchID-handNum
	Data      string    `gorm:"type:text;not null" json:"data"`
	CreatedAt time.Time `json:"createdAt"`
}

// AutoMigrate setups the DB schema
func AutoMigrate(db *gorm.DB) error {
	return db.AutoMigrate(
		&User{},
		&Match{},
		&MatchPlayer{},
		&PaipuRecord{},
	)
}
