package storage

import (
	"crypto/rand"
	"fmt"
	"log"
	"math/big"
	"strings"
	"time"
	"unicode"
	"unicode/utf8"

	"gorm.io/gorm"
)

// User represents a player account. Email and Username are both login
// identities; UsernameKey is the case-insensitive normalized lookup key.
type User struct {
	ID           uint      `gorm:"primaryKey;autoIncrement:false" json:"id"` // random sparse id, app-generated
	Email        string    `gorm:"uniqueIndex;not null;size:255" json:"email"`
	Username     string    `gorm:"not null;size:255" json:"username"`
	UsernameKey  string    `gorm:"size:255" json:"-"`
	PasswordHash string    `gorm:"not null" json:"-"`
	Rating       int       `gorm:"default:1500" json:"rating"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

// UserSession is a revocable browser login. TokenHash contains only the
// SHA-256 digest of the opaque cookie value; CSRFToken is returned to the
// authenticated frontend and must accompany state-changing requests.
type UserSession struct {
	ID        uint      `gorm:"primaryKey" json:"-"`
	TokenHash string    `gorm:"uniqueIndex;not null;size:64" json:"-"`
	UserID    uint      `gorm:"index;not null" json:"-"`
	CSRFToken string    `gorm:"not null;size:64" json:"-"`
	ExpiresAt time.Time `gorm:"index;not null" json:"-"`
	CreatedAt time.Time `json:"-"`
}

// NormalizeUsername turns a friendly visible name into its canonical display
// and case-insensitive lookup key. The API separately enforces the 2-30 rune
// length; migration callers can apply deterministic fallbacks before saving.
func NormalizeUsername(input string) (string, string) {
	input = strings.ReplaceAll(input, "@", "-at-")
	var out strings.Builder
	lastSpace := false
	lastDash := false
	for _, r := range strings.TrimSpace(input) {
		switch {
		case unicode.IsLetter(r) || unicode.IsNumber(r) || r == '_':
			out.WriteRune(r)
			lastSpace = false
			lastDash = false
		case unicode.IsSpace(r):
			if out.Len() > 0 && !lastSpace {
				out.WriteByte(' ')
				lastSpace = true
				lastDash = false
			}
		case r == '-':
			if out.Len() > 0 && !lastDash {
				out.WriteByte('-')
				lastDash = true
				lastSpace = false
			}
		default:
			if out.Len() > 0 && !lastDash {
				out.WriteByte('-')
				lastDash = true
				lastSpace = false
			}
		}
	}
	display := strings.Trim(out.String(), " -")
	return display, strings.ToLower(display)
}

func truncateRunes(value string, max int) string {
	if utf8.RuneCountInString(value) <= max {
		return value
	}
	runes := []rune(value)
	return string(runes[:max])
}

const (
	userIDMin  = 10000
	userIDSpan = 90000 // 99999 - 10000 + 1
)

// generateUserID returns a cryptographically-random id in [10000, 99999]. The
// range stays compact enough to round-trip exactly through every JSON client.
func generateUserID() (uint, error) {
	n, err := rand.Int(rand.Reader, big.NewInt(userIDSpan))
	if err != nil {
		return 0, err
	}
	return uint(n.Int64()) + userIDMin, nil
}

// BeforeCreate assigns a random sparse id when one isn't already set, so users
// get non-sequential, unguessable ids instead of an auto-increment sequence.
func (u *User) BeforeCreate(tx *gorm.DB) error {
	if u.ID == 0 {
		id, err := generateUserID()
		if err != nil {
			return err
		}
		u.ID = id
	}
	if u.Username != "" {
		u.Username, u.UsernameKey = NormalizeUsername(u.Username)
	}
	return nil
}

// Match represents a single game of Mahjong
type Match struct {
	ID        string     `gorm:"type:uuid;primaryKey" json:"id"`                       // Generated by Go UUID
	Status    string     `gorm:"size:50;not null;default:'in_progress'" json:"status"` // in_progress, completed, aborted
	StartTime time.Time  `gorm:"not null" json:"startTime"`
	EndTime   *time.Time `json:"endTime,omitempty"`

	// Important Fenghua Settings
	Ruleset   string `gorm:"size:100;not null;default:'fenghua'" json:"ruleset"`
	WallSeed  string `gorm:"type:text" json:"wallSeed,omitempty"` // For verifying replays
	ReplayURL string `gorm:"type:text" json:"replayUrl,omitempty"`
	PaipuJSON string `gorm:"type:text" json:"paipuJson,omitempty"`

	// Relationships
	Players []MatchPlayer `gorm:"foreignKey:MatchID" json:"players"`
}

// MatchPlayer is the join table recording a user's performance in a specific match
type MatchPlayer struct {
	ID      uint   `gorm:"primaryKey" json:"-"`
	MatchID string `gorm:"type:uuid;index;not null;uniqueIndex:idx_match_players_match_seat,priority:1" json:"matchId"`
	UserID  uint   `gorm:"index;not null" json:"userId"`

	// One row per seat per match; the unique index also guards against a
	// retried persist duplicating rows after an ambiguous commit.
	Seat        uint  `gorm:"not null;uniqueIndex:idx_match_players_match_seat,priority:2" json:"seat"` // 0=East, 1=South, 2=West, 3=North
	FinalScore  int32 `gorm:"not null;default:0" json:"finalScore"`
	Placement   uint  `gorm:"not null;default:0" json:"placement"` // 1st, 2nd, 3rd, 4th
	RatingDelta int   `gorm:"not null;default:0" json:"ratingDelta"`

	// Seat-composition labels mirroring the paipu players, so a dataset can
	// be filtered in SQL without parsing PaipuJSON. Bots have UserID 0.
	IsBot      bool   `gorm:"not null;default:false" json:"isBot"`
	Difficulty string `gorm:"size:32" json:"difficulty,omitempty"` // bots: "heuristic" | "rl"
	PolicyID   string `gorm:"size:512" json:"policyId,omitempty"`  // RL bots: serving checkpoint identity

	// RL decision provenance: remote-served vs heuristic-fallback decision
	// counts (pure-RL filter: fallback_decisions = 0 AND remote_decisions > 0).
	RemoteDecisions   uint64 `gorm:"not null;default:0" json:"remoteDecisions,omitempty"`
	FallbackDecisions uint64 `gorm:"not null;default:0" json:"fallbackDecisions,omitempty"`
	// Decisions automation made on this seat (bot takeover of a human seat);
	// pure-human filter: is_bot = false AND automated_decisions = 0.
	AutomatedDecisions uint64 `gorm:"not null;default:0" json:"automatedDecisions,omitempty"`

	// NOTE: deliberately no gorm relation to User (and no users foreign key):
	// bots persist with UserID 0 and historical guest matches may contain user
	// ids with no users row, so a users FK would reject those legacy records.
	// AutoMigrate drops the constraint left behind by the old relations.
}

// PaipuRecord stores a per-round paipu replay
type PaipuRecord struct {
	ID        string    `gorm:"primaryKey;size:255" json:"id"` // matchID-handNum
	Data      string    `gorm:"type:text;not null" json:"data"`
	CreatedAt time.Time `json:"createdAt"`
}

// MatchReview caches one champion's review report for a match. A new champion
// (different CheckpointID) re-reviews without destroying the old report.
type MatchReview struct {
	ID           uint      `gorm:"primaryKey" json:"-"`
	MatchID      string    `gorm:"size:255;not null;uniqueIndex:idx_match_reviews_match_ckpt,priority:1;index" json:"matchId"`
	CheckpointID string    `gorm:"size:512;not null;uniqueIndex:idx_match_reviews_match_ckpt,priority:2" json:"checkpointId"`
	ReportJSON   string    `gorm:"type:text;not null" json:"-"`
	CreatedAt    time.Time `json:"createdAt"`
}

// AutoMigrate brings the schema up to date and safely transitions legacy user
// identities to case-insensitively unique username keys.
//
// The legacy schema is detected as a `users` table that has no `email` column.
// If such a table still holds rows we FAIL CLOSED with a diagnostic, because the
// email-based model has no backfill path and migrating must never silently
// destroy or half-migrate accounts. An empty legacy table is migrated in place.
// Finally, any stale unique index on `username` (left by the old schema) is
// dropped so display names are non-unique as designed. This runs at startup, so
// a failure surfaces immediately instead of depending on an out-of-band manual
// step executed at the right moment.
func AutoMigrate(db *gorm.DB) error {
	m := db.Migrator()

	if m.HasTable(&User{}) && !m.HasColumn(&User{}, "email") {
		var count int64
		if err := db.Table("users").Count(&count).Error; err != nil {
			return fmt.Errorf("inspecting legacy users table: %w", err)
		}
		if count > 0 {
			return fmt.Errorf("refusing to migrate: legacy %q table has %d row(s) and no email column; "+
				"the email-based schema has no backfill path — migrate or remove that data, then restart", "users", count)
		}
		// Empty legacy table: AutoMigrate below adds the email column in place.
	}

	// The prior schema used username as either a unique legacy identity or a
	// non-unique display name. Remove that old index before adding/backfilling
	// the dedicated normalized key.
	if m.HasIndex(&User{}, "idx_users_username") {
		if err := m.DropIndex(&User{}, "idx_users_username"); err != nil {
			return fmt.Errorf("dropping stale unique username index: %w", err)
		}
	}

	if err := db.AutoMigrate(
		&User{},
		&UserSession{},
		&Match{},
		&MatchPlayer{},
		&PaipuRecord{},
		&MatchReview{},
	); err != nil {
		return err
	}

	if err := db.Transaction(func(tx *gorm.DB) error {
		if err := backfillUniqueUsernames(tx); err != nil {
			return err
		}
		if !tx.Migrator().HasIndex(&User{}, "idx_users_username_key") {
			if err := tx.Exec("CREATE UNIQUE INDEX idx_users_username_key ON users(username_key)").Error; err != nil {
				return fmt.Errorf("creating unique username key index: %w", err)
			}
		}
		return nil
	}); err != nil {
		return err
	}

	// Drop the users foreign key(s) the old User↔MatchPlayer relations put on
	// match_players. Bots persist with user_id 0 and guest accounts have no
	// users row, so the constraint would reject bot and historical guest rows.
	// Both historical GORM constraint names are handled; idempotent.
	for _, constraint := range []string{"fk_users_matches", "fk_match_players_user"} {
		if m.HasConstraint(&MatchPlayer{}, constraint) {
			if err := m.DropConstraint(&MatchPlayer{}, constraint); err != nil {
				return fmt.Errorf("dropping match_players users FK %q: %w", constraint, err)
			}
		}
	}

	// Backfill the legacy ruleset key: "hometown" was renamed to "fenghua" in
	// 2026-06. Idempotent — only touches rows that still hold the old value.
	if err := db.Model(&Match{}).Where("ruleset = ?", "hometown").Update("ruleset", "fenghua").Error; err != nil {
		return fmt.Errorf("backfilling legacy ruleset key: %w", err)
	}
	stats, err := backfillLegacyMatchPlayers(db)
	if err != nil {
		return err
	}
	if stats.RecoveredMatches > 0 || stats.SkippedMatches > 0 {
		log.Printf("match history backfill: recovered=%d skipped=%d", stats.RecoveredMatches, stats.SkippedMatches)
	}
	return nil
}

func backfillUniqueUsernames(db *gorm.DB) error {
	var users []User
	if err := db.Order("created_at ASC").Order("id ASC").Find(&users).Error; err != nil {
		return fmt.Errorf("loading users for username migration: %w", err)
	}
	used := make(map[string]struct{}, len(users))
	for _, user := range users {
		display, key := NormalizeUsername(user.Username)
		if utf8.RuneCountInString(display) < 2 {
			display = fmt.Sprintf("Player-%d", user.ID)
			key = strings.ToLower(display)
		}
		display = truncateRunes(display, 30)
		key = strings.ToLower(display)
		baseDisplay := display
		for suffix := 2; ; suffix++ {
			if _, exists := used[key]; !exists {
				break
			}
			tail := fmt.Sprintf("-%d", suffix)
			display = truncateRunes(baseDisplay, 30-utf8.RuneCountInString(tail)) + tail
			key = strings.ToLower(display)
		}
		used[key] = struct{}{}
		if err := db.Model(&User{}).Where("id = ?", user.ID).Updates(map[string]any{
			"username":     display,
			"username_key": key,
		}).Error; err != nil {
			return fmt.Errorf("backfilling username for user %d: %w", user.ID, err)
		}
	}
	return nil
}
