package core_test

import (
	"testing"

	"github.com/plasma/fh-mahjong/core"
	pb "github.com/plasma/fh-mahjong/proto"
	"github.com/plasma/fh-mahjong/rules"
)

func TestTileFromId(t *testing.T) {
	tests := []struct {
		id    uint32
		suit  pb.Suit
		value uint32
	}{
		{0, pb.Suit_SUIT_SOU, 1},      // First sou tile
		{35, pb.Suit_SUIT_SOU, 9},     // Last sou tile (4th copy of 9s)
		{36, pb.Suit_SUIT_MAN, 1},     // First man tile
		{72, pb.Suit_SUIT_PIN, 1},     // First pin tile
		{108, pb.Suit_SUIT_JIHAI, 1},  // East wind
		{135, pb.Suit_SUIT_JIHAI, 7},  // Chun (4th copy)
		{136, pb.Suit_SUIT_FLOWER, 1}, // Spring
		{143, pb.Suit_SUIT_FLOWER, 8}, // Bamboo
	}
	for _, tc := range tests {
		suit, value := core.TileFromId(tc.id)
		if suit != tc.suit || value != tc.value {
			t.Errorf("TileFromId(%d) = (%v, %d), want (%v, %d)", tc.id, suit, value, tc.suit, tc.value)
		}
	}
}

func TestTileFromIdConsistency(t *testing.T) {
	// Verify TileFromId matches the actual wall generated by HometownRuleset
	ruleset := &rules.HometownRuleset{}
	wall := ruleset.GetInitialWall()
	for _, tile := range wall {
		suit, value := core.TileFromId(tile.Id)
		if suit != tile.Suit || value != tile.Value {
			t.Errorf("TileFromId(%d) = (%v, %d), wall has (%v, %d)", tile.Id, suit, value, tile.Suit, tile.Value)
		}
	}
}

func TestPaipuRecorderBasicFlow(t *testing.T) {
	rec := core.NewPaipuRecorder("test-match", "hometown")

	// Add players
	rec.AddPlayer(0, "Alice", 1)
	rec.AddPlayer(1, "Bob", 2)
	rec.AddPlayer(2, "Charlie", 3)
	rec.AddPlayer(3, "Diana", 4)

	// Start a round
	deals := [4][]uint32{
		{0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48},
		{1, 5, 9, 13, 17, 21, 25, 29, 33, 37, 41, 45, 49},
		{2, 6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50},
		{3, 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51},
	}
	rec.StartRound(1, 1, 0, [2]uint32{3, 4}, "seed", nil, 7, [4]int32{25000, 25000, 25000, 25000}, deals)

	// Record actions
	rec.RecordDraw(0, 52)
	rec.RecordDiscard(0, 52)
	rec.RecordDraw(1, 53)
	rec.RecordDiscard(1, 8)

	// End round
	rec.EndRound(&core.PaipuRoundResult{
		Type:         "draw",
		ScoreChanges: []int32{0, 0, 0, 0},
	})

	// Finalize
	paipu := rec.Finalize([4]int32{25000, 25000, 25000, 25000})

	if paipu.Version != 1 {
		t.Errorf("version = %d, want 1", paipu.Version)
	}
	if len(paipu.Rounds) != 1 {
		t.Fatalf("rounds = %d, want 1", len(paipu.Rounds))
	}
	if len(paipu.Rounds[0].Actions) != 4 {
		t.Errorf("actions = %d, want 4", len(paipu.Rounds[0].Actions))
	}
	if paipu.Rounds[0].Actions[0].Act != "draw" {
		t.Errorf("first action = %q, want 'draw'", paipu.Rounds[0].Actions[0].Act)
	}
}

func TestPaipuRecorderIntegration(t *testing.T) {
	ruleset := &rules.HometownRuleset{}
	g := core.NewGame("test-paipu", ruleset)
	g.Recorder = core.NewPaipuRecorder("test-paipu", "hometown")

	err := g.Start()
	if err != nil {
		t.Fatalf("Start() error: %v", err)
	}

	// Verify recorder has a round started
	if g.Recorder.CurrentRound() == nil {
		t.Fatal("Expected currentRound to be started after Start()")
	}
	// Verify deals are recorded
	for i := 0; i < 4; i++ {
		if len(g.Recorder.CurrentRound().Deals[i]) != 13 {
			t.Errorf("Seat %d deal has %d tiles, want 13", i, len(g.Recorder.CurrentRound().Deals[i]))
		}
	}
	// Verify at least one action was recorded (the dealer's draw)
	if len(g.Recorder.CurrentRound().Actions) < 1 {
		t.Error("Expected at least 1 action (dealer draw) after Start()")
	}
	if g.Recorder.CurrentRound().Actions[0].Act != "draw" {
		t.Errorf("First action = %q, want 'draw'", g.Recorder.CurrentRound().Actions[0].Act)
	}
}
