// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/game.proto

// Defines the custom Mahjong protocols.
// Used across Go (Backend), TypeScript (Frontend), and Python (AI).

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Suit int32

const (
	Suit_SUIT_UNKNOWN Suit = 0
	Suit_SUIT_SOU     Suit = 1
	Suit_SUIT_PIN     Suit = 2
	Suit_SUIT_MAN     Suit = 3
	Suit_SUIT_JIHAI   Suit = 4
	Suit_SUIT_FLOWER  Suit = 5
)

// Enum value maps for Suit.
var (
	Suit_name = map[int32]string{
		0: "SUIT_UNKNOWN",
		1: "SUIT_SOU",
		2: "SUIT_PIN",
		3: "SUIT_MAN",
		4: "SUIT_JIHAI",
		5: "SUIT_FLOWER",
	}
	Suit_value = map[string]int32{
		"SUIT_UNKNOWN": 0,
		"SUIT_SOU":     1,
		"SUIT_PIN":     2,
		"SUIT_MAN":     3,
		"SUIT_JIHAI":   4,
		"SUIT_FLOWER":  5,
	}
)

func (x Suit) Enum() *Suit {
	p := new(Suit)
	*p = x
	return p
}

func (x Suit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Suit) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_proto_enumTypes[0].Descriptor()
}

func (Suit) Type() protoreflect.EnumType {
	return &file_proto_game_proto_enumTypes[0]
}

func (x Suit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Suit.Descriptor instead.
func (Suit) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

type ActionType int32

const (
	ActionType_ACTION_UNKNOWN ActionType = 0
	// Base Actions
	ActionType_ACTION_DRAW    ActionType = 1
	ActionType_ACTION_DISCARD ActionType = 2
	// Melds
	ActionType_ACTION_CHII ActionType = 3 // sequence
	ActionType_ACTION_PON  ActionType = 4 // triplet
	ActionType_ACTION_KAN  ActionType = 5 // quad
	// Wins
	ActionType_ACTION_TSUMO ActionType = 6 // self-draw win
	ActionType_ACTION_RON   ActionType = 7 // steal win
	// Others
	ActionType_ACTION_PASS          ActionType = 8  // pass on an opportunity to steal
	ActionType_ACTION_FLOWER_REVEAL ActionType = 9  // Fenghua rule: drawing and exposing a flower tile
	ActionType_ACTION_READY         ActionType = 10 // Signal readiness for next round after round end
	ActionType_ACTION_ACCEPT_HAITEI ActionType = 11 // Accept drawing the last tile (haitei)
	ActionType_ACTION_REFUSE_HAITEI ActionType = 12 // Refuse the last tile → ryuukyoku
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0:  "ACTION_UNKNOWN",
		1:  "ACTION_DRAW",
		2:  "ACTION_DISCARD",
		3:  "ACTION_CHII",
		4:  "ACTION_PON",
		5:  "ACTION_KAN",
		6:  "ACTION_TSUMO",
		7:  "ACTION_RON",
		8:  "ACTION_PASS",
		9:  "ACTION_FLOWER_REVEAL",
		10: "ACTION_READY",
		11: "ACTION_ACCEPT_HAITEI",
		12: "ACTION_REFUSE_HAITEI",
	}
	ActionType_value = map[string]int32{
		"ACTION_UNKNOWN":       0,
		"ACTION_DRAW":          1,
		"ACTION_DISCARD":       2,
		"ACTION_CHII":          3,
		"ACTION_PON":           4,
		"ACTION_KAN":           5,
		"ACTION_TSUMO":         6,
		"ACTION_RON":           7,
		"ACTION_PASS":          8,
		"ACTION_FLOWER_REVEAL": 9,
		"ACTION_READY":         10,
		"ACTION_ACCEPT_HAITEI": 11,
		"ACTION_REFUSE_HAITEI": 12,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_proto_enumTypes[1].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_proto_game_proto_enumTypes[1]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

type MeldDirection int32

const (
	MeldDirection_MELD_DIRECTION_UNKNOWN MeldDirection = 0
	MeldDirection_MELD_DIRECTION_RIGHT   MeldDirection = 1
	MeldDirection_MELD_DIRECTION_ACROSS  MeldDirection = 2
	MeldDirection_MELD_DIRECTION_LEFT    MeldDirection = 3
)

// Enum value maps for MeldDirection.
var (
	MeldDirection_name = map[int32]string{
		0: "MELD_DIRECTION_UNKNOWN",
		1: "MELD_DIRECTION_RIGHT",
		2: "MELD_DIRECTION_ACROSS",
		3: "MELD_DIRECTION_LEFT",
	}
	MeldDirection_value = map[string]int32{
		"MELD_DIRECTION_UNKNOWN": 0,
		"MELD_DIRECTION_RIGHT":   1,
		"MELD_DIRECTION_ACROSS":  2,
		"MELD_DIRECTION_LEFT":    3,
	}
)

func (x MeldDirection) Enum() *MeldDirection {
	p := new(MeldDirection)
	*p = x
	return p
}

func (x MeldDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MeldDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_proto_enumTypes[2].Descriptor()
}

func (MeldDirection) Type() protoreflect.EnumType {
	return &file_proto_game_proto_enumTypes[2]
}

func (x MeldDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MeldDirection.Descriptor instead.
func (MeldDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

type GamePhase int32

const (
	GamePhase_PHASE_INIT          GamePhase = 0
	GamePhase_PHASE_DEAL          GamePhase = 1
	GamePhase_PHASE_PLAYER_TURN   GamePhase = 2 // Waiting for them to discard
	GamePhase_PHASE_WAIT_DISCARDS GamePhase = 3 // Someone discarded, waiting a few sec for steals
	GamePhase_PHASE_ROUND_END     GamePhase = 4
)

// Enum value maps for GamePhase.
var (
	GamePhase_name = map[int32]string{
		0: "PHASE_INIT",
		1: "PHASE_DEAL",
		2: "PHASE_PLAYER_TURN",
		3: "PHASE_WAIT_DISCARDS",
		4: "PHASE_ROUND_END",
	}
	GamePhase_value = map[string]int32{
		"PHASE_INIT":          0,
		"PHASE_DEAL":          1,
		"PHASE_PLAYER_TURN":   2,
		"PHASE_WAIT_DISCARDS": 3,
		"PHASE_ROUND_END":     4,
	}
)

func (x GamePhase) Enum() *GamePhase {
	p := new(GamePhase)
	*p = x
	return p
}

func (x GamePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GamePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_proto_enumTypes[3].Descriptor()
}

func (GamePhase) Type() protoreflect.EnumType {
	return &file_proto_game_proto_enumTypes[3]
}

func (x GamePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GamePhase.Descriptor instead.
func (GamePhase) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

type Tile struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the tile (0-143). 0-135 standard, 136-143 flowers.
	Id   uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Suit Suit   `protobuf:"varint,2,opt,name=suit,proto3,enum=game.Suit" json:"suit,omitempty"`
	// For suits 1-3, value is 1-9. Wait! In mahjong it's 1-9 for sou/pin/man,
	// 1-7 for jihai (East, South, West, North, Haku, Hatsu, Chun).
	Value         uint32 `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tile) Reset() {
	*x = Tile{}
	mi := &file_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tile) ProtoMessage() {}

func (x *Tile) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tile.ProtoReflect.Descriptor instead.
func (*Tile) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *Tile) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Tile) GetSuit() Suit {
	if x != nil {
		return x.Suit
	}
	return Suit_SUIT_UNKNOWN
}

func (x *Tile) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PlayerAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ActionType             `protobuf:"varint,1,opt,name=type,proto3,enum=game.ActionType" json:"type,omitempty"`
	// The tile being acted upon (e.g. the tile being discarded or stolen).
	Tile *Tile `protobuf:"bytes,2,opt,name=tile,proto3" json:"tile,omitempty"`
	// The subset of hand tiles revealed to complete the action (e.g. 2 tiles for a Chow/Pong).
	MeldTiles []*Tile `protobuf:"bytes,3,rep,name=meld_tiles,json=meldTiles,proto3" json:"meld_tiles,omitempty"`
	// Which player is targeted (0-3).
	// (e.g. Who did we Ron from? Who did we Pong from?)
	TargetPlayer uint32 `protobuf:"varint,4,opt,name=target_player,json=targetPlayer,proto3" json:"target_player,omitempty"`
	// Context flags for win evaluations
	IsRobbingKong  bool `protobuf:"varint,5,opt,name=is_robbing_kong,json=isRobbingKong,proto3" json:"is_robbing_kong,omitempty"`
	IsBottomTile   bool `protobuf:"varint,6,opt,name=is_bottom_tile,json=isBottomTile,proto3" json:"is_bottom_tile,omitempty"`
	IsBloomingKong bool `protobuf:"varint,7,opt,name=is_blooming_kong,json=isBloomingKong,proto3" json:"is_blooming_kong,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerAction) Reset() {
	*x = PlayerAction{}
	mi := &file_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerAction) ProtoMessage() {}

func (x *PlayerAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerAction.ProtoReflect.Descriptor instead.
func (*PlayerAction) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerAction) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACTION_UNKNOWN
}

func (x *PlayerAction) GetTile() *Tile {
	if x != nil {
		return x.Tile
	}
	return nil
}

func (x *PlayerAction) GetMeldTiles() []*Tile {
	if x != nil {
		return x.MeldTiles
	}
	return nil
}

func (x *PlayerAction) GetTargetPlayer() uint32 {
	if x != nil {
		return x.TargetPlayer
	}
	return 0
}

func (x *PlayerAction) GetIsRobbingKong() bool {
	if x != nil {
		return x.IsRobbingKong
	}
	return false
}

func (x *PlayerAction) GetIsBottomTile() bool {
	if x != nil {
		return x.IsBottomTile
	}
	return false
}

func (x *PlayerAction) GetIsBloomingKong() bool {
	if x != nil {
		return x.IsBloomingKong
	}
	return false
}

type Meld struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ActionType             `protobuf:"varint,1,opt,name=type,proto3,enum=game.ActionType" json:"type,omitempty"`
	Tiles []*Tile                `protobuf:"bytes,2,rep,name=tiles,proto3" json:"tiles,omitempty"`
	// Relative direction of the player who discarded the called tile.
	// 1: Right (shimocha), 2: Across (toimen), 3: Left (kamicha).
	CalledDirection MeldDirection `protobuf:"varint,3,opt,name=called_direction,json=calledDirection,proto3,enum=game.MeldDirection" json:"called_direction,omitempty"`
	// The ID of the specific tile that was called (useful for UI rendering to know which one to rotate sideways).
	CalledTileId  uint32 `protobuf:"varint,4,opt,name=called_tile_id,json=calledTileId,proto3" json:"called_tile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Meld) Reset() {
	*x = Meld{}
	mi := &file_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Meld) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Meld) ProtoMessage() {}

func (x *Meld) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Meld.ProtoReflect.Descriptor instead.
func (*Meld) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *Meld) GetType() ActionType {
	if x != nil {
		return x.Type
	}
	return ActionType_ACTION_UNKNOWN
}

func (x *Meld) GetTiles() []*Tile {
	if x != nil {
		return x.Tiles
	}
	return nil
}

func (x *Meld) GetCalledDirection() MeldDirection {
	if x != nil {
		return x.CalledDirection
	}
	return MeldDirection_MELD_DIRECTION_UNKNOWN
}

func (x *Meld) GetCalledTileId() uint32 {
	if x != nil {
		return x.CalledTileId
	}
	return 0
}

type PlayerState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seat  uint32                 `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"` // 0=East, 1=South, 2=West, 3=North
	// Number of points the player has
	Score int32 `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	// The tiles currently held in the closed hand.
	// In a broadcast to other players, this might be empty for security.
	ClosedHand []*Tile `protobuf:"bytes,3,rep,name=closed_hand,json=closedHand,proto3" json:"closed_hand,omitempty"`
	// The number of tiles in the hand (always public).
	HandSize uint32 `protobuf:"varint,4,opt,name=hand_size,json=handSize,proto3" json:"hand_size,omitempty"`
	// Opened melds (Chows, Pongs, Kongs)
	OpenMelds []*Meld `protobuf:"bytes,5,rep,name=open_melds,json=openMelds,proto3" json:"open_melds,omitempty"`
	// Discarded tiles pool
	Discards []*Tile `protobuf:"bytes,6,rep,name=discards,proto3" json:"discards,omitempty"`
	// Track the player's specific seat wind (1: East, 2: South, 3: West, 4: North)
	SeatWind uint32 `protobuf:"varint,7,opt,name=seat_wind,json=seatWind,proto3" json:"seat_wind,omitempty"`
	// Track the specific flower tiles the player has melded (IDs 136-143)
	FlowerMelds []*Tile `protobuf:"bytes,8,rep,name=flower_melds,json=flowerMelds,proto3" json:"flower_melds,omitempty"`
	// Kong bonus context flags (set by game loop before calling EvaluateHand)
	HasBuddingDirectKong  bool `protobuf:"varint,9,opt,name=has_budding_direct_kong,json=hasBuddingDirectKong,proto3" json:"has_budding_direct_kong,omitempty"`
	HasBloomingDirectKong bool `protobuf:"varint,10,opt,name=has_blooming_direct_kong,json=hasBloomingDirectKong,proto3" json:"has_blooming_direct_kong,omitempty"`
	HasBuddingClosedKong  bool `protobuf:"varint,11,opt,name=has_budding_closed_kong,json=hasBuddingClosedKong,proto3" json:"has_budding_closed_kong,omitempty"`
	HasBloomingClosedKong bool `protobuf:"varint,12,opt,name=has_blooming_closed_kong,json=hasBloomingClosedKong,proto3" json:"has_blooming_closed_kong,omitempty"`
	HasBuddingRiskyKong   bool `protobuf:"varint,13,opt,name=has_budding_risky_kong,json=hasBuddingRiskyKong,proto3" json:"has_budding_risky_kong,omitempty"`
	HasBloomingRiskyKong  bool `protobuf:"varint,14,opt,name=has_blooming_risky_kong,json=hasBloomingRiskyKong,proto3" json:"has_blooming_risky_kong,omitempty"`
	HasBloomingFlowerKong bool `protobuf:"varint,15,opt,name=has_blooming_flower_kong,json=hasBloomingFlowerKong,proto3" json:"has_blooming_flower_kong,omitempty"`
	// Actions the player is currently allowed to take
	ValidActions []*PlayerAction `protobuf:"bytes,16,rep,name=valid_actions,json=validActions,proto3" json:"valid_actions,omitempty"`
	// The specific ID of the tile that was just drawn (used to render the gap on frontend).
	// optional prevents Javascript dropping the number 0 (since Tile ID 0 = 1m).
	DrawnTileId   *int32 `protobuf:"varint,17,opt,name=drawn_tile_id,json=drawnTileId,proto3,oneof" json:"drawn_tile_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerState) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *PlayerState) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *PlayerState) GetClosedHand() []*Tile {
	if x != nil {
		return x.ClosedHand
	}
	return nil
}

func (x *PlayerState) GetHandSize() uint32 {
	if x != nil {
		return x.HandSize
	}
	return 0
}

func (x *PlayerState) GetOpenMelds() []*Meld {
	if x != nil {
		return x.OpenMelds
	}
	return nil
}

func (x *PlayerState) GetDiscards() []*Tile {
	if x != nil {
		return x.Discards
	}
	return nil
}

func (x *PlayerState) GetSeatWind() uint32 {
	if x != nil {
		return x.SeatWind
	}
	return 0
}

func (x *PlayerState) GetFlowerMelds() []*Tile {
	if x != nil {
		return x.FlowerMelds
	}
	return nil
}

func (x *PlayerState) GetHasBuddingDirectKong() bool {
	if x != nil {
		return x.HasBuddingDirectKong
	}
	return false
}

func (x *PlayerState) GetHasBloomingDirectKong() bool {
	if x != nil {
		return x.HasBloomingDirectKong
	}
	return false
}

func (x *PlayerState) GetHasBuddingClosedKong() bool {
	if x != nil {
		return x.HasBuddingClosedKong
	}
	return false
}

func (x *PlayerState) GetHasBloomingClosedKong() bool {
	if x != nil {
		return x.HasBloomingClosedKong
	}
	return false
}

func (x *PlayerState) GetHasBuddingRiskyKong() bool {
	if x != nil {
		return x.HasBuddingRiskyKong
	}
	return false
}

func (x *PlayerState) GetHasBloomingRiskyKong() bool {
	if x != nil {
		return x.HasBloomingRiskyKong
	}
	return false
}

func (x *PlayerState) GetHasBloomingFlowerKong() bool {
	if x != nil {
		return x.HasBloomingFlowerKong
	}
	return false
}

func (x *PlayerState) GetValidActions() []*PlayerAction {
	if x != nil {
		return x.ValidActions
	}
	return nil
}

func (x *PlayerState) GetDrawnTileId() int32 {
	if x != nil && x.DrawnTileId != nil {
		return *x.DrawnTileId
	}
	return 0
}

type GameState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID for the match
	MatchId string    `protobuf:"bytes,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Phase   GamePhase `protobuf:"varint,2,opt,name=phase,proto3,enum=game.GamePhase" json:"phase,omitempty"`
	// Who's turn is it right now? (0-3)
	ActivePlayer uint32 `protobuf:"varint,3,opt,name=active_player,json=activePlayer,proto3" json:"active_player,omitempty"`
	// The 4 players.
	Players []*PlayerState `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	// Number of tiles left in the wall
	WallCount uint32 `protobuf:"varint,5,opt,name=wall_count,json=wallCount,proto3" json:"wall_count,omitempty"`
	// Current hand number (e.g. East 1 = 1, East 2 = 2)
	HandNum uint32 `protobuf:"varint,6,opt,name=hand_num,json=handNum,proto3" json:"hand_num,omitempty"`
	// The current active discard (if in PHASE_WAIT_DISCARDS)
	ActiveDiscard *Tile `protobuf:"bytes,7,opt,name=active_discard,json=activeDiscard,proto3" json:"active_discard,omitempty"`
	// The current active wild tiles for this round
	WildTiles []*Tile `protobuf:"bytes,8,rep,name=wild_tiles,json=wildTiles,proto3" json:"wild_tiles,omitempty"`
	// The prevailing (round) wind for Fenghua Mahjong (1=East, 2=South, 3=West, 4=North)
	PrevailingWind uint32 `protobuf:"varint,11,opt,name=prevailing_wind,json=prevailingWind,proto3" json:"prevailing_wind,omitempty"`
	// The base64-encoded MT19937 seed used to shuffle the wall (for replay verification)
	WallSeed string `protobuf:"bytes,12,opt,name=wall_seed,json=wallSeed,proto3" json:"wall_seed,omitempty"`
	// Round result data (populated when phase = PHASE_ROUND_END)
	RoundResult *RoundResult `protobuf:"bytes,13,opt,name=round_result,json=roundResult,proto3" json:"round_result,omitempty"`
	// Per-player ready state for next round (length 4, indexed by seat)
	PlayerReady []bool `protobuf:"varint,14,rep,packed,name=player_ready,json=playerReady,proto3" json:"player_ready,omitempty"`
	// Dice sum (2-12) rolled at the start of each round
	DiceSum uint32 `protobuf:"varint,15,opt,name=dice_sum,json=diceSum,proto3" json:"dice_sum,omitempty"`
	// Number of wangpai (dead wall) stacks reserved at the tail of the wall
	WangpaiStacks uint32 `protobuf:"varint,16,opt,name=wangpai_stacks,json=wangpaiStacks,proto3" json:"wangpai_stacks,omitempty"`
	// True when the active player is being offered the haitei (last drawable) tile
	IsHaitei bool `protobuf:"varint,17,opt,name=is_haitei,json=isHaitei,proto3" json:"is_haitei,omitempty"`
	// Individual dice rolled at the start of each round
	Dice1 uint32 `protobuf:"varint,18,opt,name=dice1,proto3" json:"dice1,omitempty"`
	Dice2 uint32 `protobuf:"varint,19,opt,name=dice2,proto3" json:"dice2,omitempty"`
	// Current number of drawable tiles left in the wangpai zone
	WangpaiTilesLeft uint32 `protobuf:"varint,20,opt,name=wangpai_tiles_left,json=wangpaiTilesLeft,proto3" json:"wangpai_tiles_left,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameState) GetMatchId() string {
	if x != nil {
		return x.MatchId
	}
	return ""
}

func (x *GameState) GetPhase() GamePhase {
	if x != nil {
		return x.Phase
	}
	return GamePhase_PHASE_INIT
}

func (x *GameState) GetActivePlayer() uint32 {
	if x != nil {
		return x.ActivePlayer
	}
	return 0
}

func (x *GameState) GetPlayers() []*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameState) GetWallCount() uint32 {
	if x != nil {
		return x.WallCount
	}
	return 0
}

func (x *GameState) GetHandNum() uint32 {
	if x != nil {
		return x.HandNum
	}
	return 0
}

func (x *GameState) GetActiveDiscard() *Tile {
	if x != nil {
		return x.ActiveDiscard
	}
	return nil
}

func (x *GameState) GetWildTiles() []*Tile {
	if x != nil {
		return x.WildTiles
	}
	return nil
}

func (x *GameState) GetPrevailingWind() uint32 {
	if x != nil {
		return x.PrevailingWind
	}
	return 0
}

func (x *GameState) GetWallSeed() string {
	if x != nil {
		return x.WallSeed
	}
	return ""
}

func (x *GameState) GetRoundResult() *RoundResult {
	if x != nil {
		return x.RoundResult
	}
	return nil
}

func (x *GameState) GetPlayerReady() []bool {
	if x != nil {
		return x.PlayerReady
	}
	return nil
}

func (x *GameState) GetDiceSum() uint32 {
	if x != nil {
		return x.DiceSum
	}
	return 0
}

func (x *GameState) GetWangpaiStacks() uint32 {
	if x != nil {
		return x.WangpaiStacks
	}
	return 0
}

func (x *GameState) GetIsHaitei() bool {
	if x != nil {
		return x.IsHaitei
	}
	return false
}

func (x *GameState) GetDice1() uint32 {
	if x != nil {
		return x.Dice1
	}
	return 0
}

func (x *GameState) GetDice2() uint32 {
	if x != nil {
		return x.Dice2
	}
	return 0
}

func (x *GameState) GetWangpaiTilesLeft() uint32 {
	if x != nil {
		return x.WangpaiTilesLeft
	}
	return 0
}

type ScoreEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatternName   string                 `protobuf:"bytes,1,opt,name=pattern_name,json=patternName,proto3" json:"pattern_name,omitempty"` // e.g. "Base Point (坐台)", "Pure One Suit (清一色)"
	Points        int32                  `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreEntry) Reset() {
	*x = ScoreEntry{}
	mi := &file_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreEntry) ProtoMessage() {}

func (x *ScoreEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreEntry.ProtoReflect.Descriptor instead.
func (*ScoreEntry) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *ScoreEntry) GetPatternName() string {
	if x != nil {
		return x.PatternName
	}
	return ""
}

func (x *ScoreEntry) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type PlayerPayout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seat          uint32                 `protobuf:"varint,1,opt,name=seat,proto3" json:"seat,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` // negative = pays, positive = receives
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerPayout) Reset() {
	*x = PlayerPayout{}
	mi := &file_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPayout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPayout) ProtoMessage() {}

func (x *PlayerPayout) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPayout.ProtoReflect.Descriptor instead.
func (*PlayerPayout) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerPayout) GetSeat() uint32 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *PlayerPayout) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RoundResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WinnerSeat    uint32                 `protobuf:"varint,1,opt,name=winner_seat,json=winnerSeat,proto3" json:"winner_seat,omitempty"`
	WinType       ActionType             `protobuf:"varint,2,opt,name=win_type,json=winType,proto3,enum=game.ActionType" json:"win_type,omitempty"` // ACTION_TSUMO or ACTION_RON
	DiscarderSeat uint32                 `protobuf:"varint,3,opt,name=discarder_seat,json=discarderSeat,proto3" json:"discarder_seat,omitempty"`    // Only meaningful for Ron
	WinningHand   []*Tile                `protobuf:"bytes,4,rep,name=winning_hand,json=winningHand,proto3" json:"winning_hand,omitempty"`           // Winner's closed hand tiles
	WinningMelds  []*Meld                `protobuf:"bytes,5,rep,name=winning_melds,json=winningMelds,proto3" json:"winning_melds,omitempty"`        // Winner's open melds
	WinTile       *Tile                  `protobuf:"bytes,6,opt,name=win_tile,json=winTile,proto3" json:"win_tile,omitempty"`                       // The completing tile
	Breakdown     []*ScoreEntry          `protobuf:"bytes,7,rep,name=breakdown,proto3" json:"breakdown,omitempty"`                                  // Pattern-by-pattern scoring breakdown
	TotalScore    int32                  `protobuf:"varint,8,opt,name=total_score,json=totalScore,proto3" json:"total_score,omitempty"`
	Payouts       []*PlayerPayout        `protobuf:"bytes,9,rep,name=payouts,proto3" json:"payouts,omitempty"`
	IsDraw        bool                   `protobuf:"varint,10,opt,name=is_draw,json=isDraw,proto3" json:"is_draw,omitempty"` // Exhaustive draw (no winner)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundResult) Reset() {
	*x = RoundResult{}
	mi := &file_proto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundResult) ProtoMessage() {}

func (x *RoundResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundResult.ProtoReflect.Descriptor instead.
func (*RoundResult) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *RoundResult) GetWinnerSeat() uint32 {
	if x != nil {
		return x.WinnerSeat
	}
	return 0
}

func (x *RoundResult) GetWinType() ActionType {
	if x != nil {
		return x.WinType
	}
	return ActionType_ACTION_UNKNOWN
}

func (x *RoundResult) GetDiscarderSeat() uint32 {
	if x != nil {
		return x.DiscarderSeat
	}
	return 0
}

func (x *RoundResult) GetWinningHand() []*Tile {
	if x != nil {
		return x.WinningHand
	}
	return nil
}

func (x *RoundResult) GetWinningMelds() []*Meld {
	if x != nil {
		return x.WinningMelds
	}
	return nil
}

func (x *RoundResult) GetWinTile() *Tile {
	if x != nil {
		return x.WinTile
	}
	return nil
}

func (x *RoundResult) GetBreakdown() []*ScoreEntry {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

func (x *RoundResult) GetTotalScore() int32 {
	if x != nil {
		return x.TotalScore
	}
	return 0
}

func (x *RoundResult) GetPayouts() []*PlayerPayout {
	if x != nil {
		return x.Payouts
	}
	return nil
}

func (x *RoundResult) GetIsDraw() bool {
	if x != nil {
		return x.IsDraw
	}
	return false
}

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\x04game\"L\n" +
	"\x04Tile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1e\n" +
	"\x04suit\x18\x02 \x01(\x0e2\n" +
	".game.SuitR\x04suit\x12\x14\n" +
	"\x05value\x18\x03 \x01(\rR\x05value\"\x9c\x02\n" +
	"\fPlayerAction\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.game.ActionTypeR\x04type\x12\x1e\n" +
	"\x04tile\x18\x02 \x01(\v2\n" +
	".game.TileR\x04tile\x12)\n" +
	"\n" +
	"meld_tiles\x18\x03 \x03(\v2\n" +
	".game.TileR\tmeldTiles\x12#\n" +
	"\rtarget_player\x18\x04 \x01(\rR\ftargetPlayer\x12&\n" +
	"\x0fis_robbing_kong\x18\x05 \x01(\bR\risRobbingKong\x12$\n" +
	"\x0eis_bottom_tile\x18\x06 \x01(\bR\fisBottomTile\x12(\n" +
	"\x10is_blooming_kong\x18\a \x01(\bR\x0eisBloomingKong\"\xb4\x01\n" +
	"\x04Meld\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.game.ActionTypeR\x04type\x12 \n" +
	"\x05tiles\x18\x02 \x03(\v2\n" +
	".game.TileR\x05tiles\x12>\n" +
	"\x10called_direction\x18\x03 \x01(\x0e2\x13.game.MeldDirectionR\x0fcalledDirection\x12$\n" +
	"\x0ecalled_tile_id\x18\x04 \x01(\rR\fcalledTileId\"\x99\x06\n" +
	"\vPlayerState\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\rR\x04seat\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12+\n" +
	"\vclosed_hand\x18\x03 \x03(\v2\n" +
	".game.TileR\n" +
	"closedHand\x12\x1b\n" +
	"\thand_size\x18\x04 \x01(\rR\bhandSize\x12)\n" +
	"\n" +
	"open_melds\x18\x05 \x03(\v2\n" +
	".game.MeldR\topenMelds\x12&\n" +
	"\bdiscards\x18\x06 \x03(\v2\n" +
	".game.TileR\bdiscards\x12\x1b\n" +
	"\tseat_wind\x18\a \x01(\rR\bseatWind\x12-\n" +
	"\fflower_melds\x18\b \x03(\v2\n" +
	".game.TileR\vflowerMelds\x125\n" +
	"\x17has_budding_direct_kong\x18\t \x01(\bR\x14hasBuddingDirectKong\x127\n" +
	"\x18has_blooming_direct_kong\x18\n" +
	" \x01(\bR\x15hasBloomingDirectKong\x125\n" +
	"\x17has_budding_closed_kong\x18\v \x01(\bR\x14hasBuddingClosedKong\x127\n" +
	"\x18has_blooming_closed_kong\x18\f \x01(\bR\x15hasBloomingClosedKong\x123\n" +
	"\x16has_budding_risky_kong\x18\r \x01(\bR\x13hasBuddingRiskyKong\x125\n" +
	"\x17has_blooming_risky_kong\x18\x0e \x01(\bR\x14hasBloomingRiskyKong\x127\n" +
	"\x18has_blooming_flower_kong\x18\x0f \x01(\bR\x15hasBloomingFlowerKong\x127\n" +
	"\rvalid_actions\x18\x10 \x03(\v2\x12.game.PlayerActionR\fvalidActions\x12'\n" +
	"\rdrawn_tile_id\x18\x11 \x01(\x05H\x00R\vdrawnTileId\x88\x01\x01B\x10\n" +
	"\x0e_drawn_tile_id\"\x8f\x05\n" +
	"\tGameState\x12\x19\n" +
	"\bmatch_id\x18\x01 \x01(\tR\amatchId\x12%\n" +
	"\x05phase\x18\x02 \x01(\x0e2\x0f.game.GamePhaseR\x05phase\x12#\n" +
	"\ractive_player\x18\x03 \x01(\rR\factivePlayer\x12+\n" +
	"\aplayers\x18\x04 \x03(\v2\x11.game.PlayerStateR\aplayers\x12\x1d\n" +
	"\n" +
	"wall_count\x18\x05 \x01(\rR\twallCount\x12\x19\n" +
	"\bhand_num\x18\x06 \x01(\rR\ahandNum\x121\n" +
	"\x0eactive_discard\x18\a \x01(\v2\n" +
	".game.TileR\ractiveDiscard\x12)\n" +
	"\n" +
	"wild_tiles\x18\b \x03(\v2\n" +
	".game.TileR\twildTiles\x12'\n" +
	"\x0fprevailing_wind\x18\v \x01(\rR\x0eprevailingWind\x12\x1b\n" +
	"\twall_seed\x18\f \x01(\tR\bwallSeed\x124\n" +
	"\fround_result\x18\r \x01(\v2\x11.game.RoundResultR\vroundResult\x12!\n" +
	"\fplayer_ready\x18\x0e \x03(\bR\vplayerReady\x12\x19\n" +
	"\bdice_sum\x18\x0f \x01(\rR\adiceSum\x12%\n" +
	"\x0ewangpai_stacks\x18\x10 \x01(\rR\rwangpaiStacks\x12\x1b\n" +
	"\tis_haitei\x18\x11 \x01(\bR\bisHaitei\x12\x14\n" +
	"\x05dice1\x18\x12 \x01(\rR\x05dice1\x12\x14\n" +
	"\x05dice2\x18\x13 \x01(\rR\x05dice2\x12,\n" +
	"\x12wangpai_tiles_left\x18\x14 \x01(\rR\x10wangpaiTilesLeft\"G\n" +
	"\n" +
	"ScoreEntry\x12!\n" +
	"\fpattern_name\x18\x01 \x01(\tR\vpatternName\x12\x16\n" +
	"\x06points\x18\x02 \x01(\x05R\x06points\":\n" +
	"\fPlayerPayout\x12\x12\n" +
	"\x04seat\x18\x01 \x01(\rR\x04seat\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"\xa1\x03\n" +
	"\vRoundResult\x12\x1f\n" +
	"\vwinner_seat\x18\x01 \x01(\rR\n" +
	"winnerSeat\x12+\n" +
	"\bwin_type\x18\x02 \x01(\x0e2\x10.game.ActionTypeR\awinType\x12%\n" +
	"\x0ediscarder_seat\x18\x03 \x01(\rR\rdiscarderSeat\x12-\n" +
	"\fwinning_hand\x18\x04 \x03(\v2\n" +
	".game.TileR\vwinningHand\x12/\n" +
	"\rwinning_melds\x18\x05 \x03(\v2\n" +
	".game.MeldR\fwinningMelds\x12%\n" +
	"\bwin_tile\x18\x06 \x01(\v2\n" +
	".game.TileR\awinTile\x12.\n" +
	"\tbreakdown\x18\a \x03(\v2\x10.game.ScoreEntryR\tbreakdown\x12\x1f\n" +
	"\vtotal_score\x18\b \x01(\x05R\n" +
	"totalScore\x12,\n" +
	"\apayouts\x18\t \x03(\v2\x12.game.PlayerPayoutR\apayouts\x12\x17\n" +
	"\ais_draw\x18\n" +
	" \x01(\bR\x06isDraw*c\n" +
	"\x04Suit\x12\x10\n" +
	"\fSUIT_UNKNOWN\x10\x00\x12\f\n" +
	"\bSUIT_SOU\x10\x01\x12\f\n" +
	"\bSUIT_PIN\x10\x02\x12\f\n" +
	"\bSUIT_MAN\x10\x03\x12\x0e\n" +
	"\n" +
	"SUIT_JIHAI\x10\x04\x12\x0f\n" +
	"\vSUIT_FLOWER\x10\x05*\x89\x02\n" +
	"\n" +
	"ActionType\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vACTION_DRAW\x10\x01\x12\x12\n" +
	"\x0eACTION_DISCARD\x10\x02\x12\x0f\n" +
	"\vACTION_CHII\x10\x03\x12\x0e\n" +
	"\n" +
	"ACTION_PON\x10\x04\x12\x0e\n" +
	"\n" +
	"ACTION_KAN\x10\x05\x12\x10\n" +
	"\fACTION_TSUMO\x10\x06\x12\x0e\n" +
	"\n" +
	"ACTION_RON\x10\a\x12\x0f\n" +
	"\vACTION_PASS\x10\b\x12\x18\n" +
	"\x14ACTION_FLOWER_REVEAL\x10\t\x12\x10\n" +
	"\fACTION_READY\x10\n" +
	"\x12\x18\n" +
	"\x14ACTION_ACCEPT_HAITEI\x10\v\x12\x18\n" +
	"\x14ACTION_REFUSE_HAITEI\x10\f*y\n" +
	"\rMeldDirection\x12\x1a\n" +
	"\x16MELD_DIRECTION_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14MELD_DIRECTION_RIGHT\x10\x01\x12\x19\n" +
	"\x15MELD_DIRECTION_ACROSS\x10\x02\x12\x17\n" +
	"\x13MELD_DIRECTION_LEFT\x10\x03*p\n" +
	"\tGamePhase\x12\x0e\n" +
	"\n" +
	"PHASE_INIT\x10\x00\x12\x0e\n" +
	"\n" +
	"PHASE_DEAL\x10\x01\x12\x15\n" +
	"\x11PHASE_PLAYER_TURN\x10\x02\x12\x17\n" +
	"\x13PHASE_WAIT_DISCARDS\x10\x03\x12\x13\n" +
	"\x0fPHASE_ROUND_END\x10\x04B)Z'github.com/plasma/fh-mahjong/proto/gameb\x06proto3"

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData []byte
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)))
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_game_proto_goTypes = []any{
	(Suit)(0),            // 0: game.Suit
	(ActionType)(0),      // 1: game.ActionType
	(MeldDirection)(0),   // 2: game.MeldDirection
	(GamePhase)(0),       // 3: game.GamePhase
	(*Tile)(nil),         // 4: game.Tile
	(*PlayerAction)(nil), // 5: game.PlayerAction
	(*Meld)(nil),         // 6: game.Meld
	(*PlayerState)(nil),  // 7: game.PlayerState
	(*GameState)(nil),    // 8: game.GameState
	(*ScoreEntry)(nil),   // 9: game.ScoreEntry
	(*PlayerPayout)(nil), // 10: game.PlayerPayout
	(*RoundResult)(nil),  // 11: game.RoundResult
}
var file_proto_game_proto_depIdxs = []int32{
	0,  // 0: game.Tile.suit:type_name -> game.Suit
	1,  // 1: game.PlayerAction.type:type_name -> game.ActionType
	4,  // 2: game.PlayerAction.tile:type_name -> game.Tile
	4,  // 3: game.PlayerAction.meld_tiles:type_name -> game.Tile
	1,  // 4: game.Meld.type:type_name -> game.ActionType
	4,  // 5: game.Meld.tiles:type_name -> game.Tile
	2,  // 6: game.Meld.called_direction:type_name -> game.MeldDirection
	4,  // 7: game.PlayerState.closed_hand:type_name -> game.Tile
	6,  // 8: game.PlayerState.open_melds:type_name -> game.Meld
	4,  // 9: game.PlayerState.discards:type_name -> game.Tile
	4,  // 10: game.PlayerState.flower_melds:type_name -> game.Tile
	5,  // 11: game.PlayerState.valid_actions:type_name -> game.PlayerAction
	3,  // 12: game.GameState.phase:type_name -> game.GamePhase
	7,  // 13: game.GameState.players:type_name -> game.PlayerState
	4,  // 14: game.GameState.active_discard:type_name -> game.Tile
	4,  // 15: game.GameState.wild_tiles:type_name -> game.Tile
	11, // 16: game.GameState.round_result:type_name -> game.RoundResult
	1,  // 17: game.RoundResult.win_type:type_name -> game.ActionType
	4,  // 18: game.RoundResult.winning_hand:type_name -> game.Tile
	6,  // 19: game.RoundResult.winning_melds:type_name -> game.Meld
	4,  // 20: game.RoundResult.win_tile:type_name -> game.Tile
	9,  // 21: game.RoundResult.breakdown:type_name -> game.ScoreEntry
	10, // 22: game.RoundResult.payouts:type_name -> game.PlayerPayout
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	file_proto_game_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		EnumInfos:         file_proto_game_proto_enumTypes,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
