package models

import (
	"time"

	"gorm.io/gorm"
)

// User represents a player account in the system
type User struct {
	ID           uint      `gorm:"primaryKey" json:"id"`
	Username     string    `gorm:"uniqueIndex;not null;size:255" json:"username"`
	PasswordHash string    `gorm:"not null" json:"-"`          // Never serialize to JSON
	Rating       int       `gorm:"default:1500" json:"rating"` // Elo rating
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`

	// Relationships
	Matches []MatchPlayer `gorm:"foreignKey:UserID" json:"-"`
}

// Match represents a single game of Mahjong
type Match struct {
	ID        string     `gorm:"type:uuid;primaryKey" json:"id"`                       // Generated by Go UUID
	Status    string     `gorm:"size:50;not null;default:'in_progress'" json:"status"` // in_progress, completed, aborted
	StartTime time.Time  `gorm:"not null" json:"startTime"`
	EndTime   *time.Time `json:"endTime,omitempty"`

	// Important Fenghua Settings
	Ruleset   string `gorm:"size:100;not null;default:'hometown'" json:"ruleset"`
	WallSeed  string `gorm:"type:text" json:"wallSeed,omitempty"` // For verifying replays
	ReplayURL string `gorm:"type:text" json:"replayUrl,omitempty"`

	// Relationships
	Players []MatchPlayer `gorm:"foreignKey:MatchID" json:"players"`
}

// MatchPlayer is the join table recording a user's performance in a specific match
type MatchPlayer struct {
	ID      uint   `gorm:"primaryKey" json:"-"`
	MatchID string `gorm:"type:uuid;index;not null" json:"matchId"`
	UserID  uint   `gorm:"index;not null" json:"userId"`

	Seat        uint  `gorm:"not null" json:"seat"` // 0=East, 1=South, 2=West, 3=North
	FinalScore  int32 `gorm:"not null;default:0" json:"finalScore"`
	Placement   uint  `gorm:"not null;default:0" json:"placement"` // 1st, 2nd, 3rd, 4th
	RatingDelta int   `gorm:"not null;default:0" json:"ratingDelta"`

	// Eager-loaded user info for match history API
	User User `gorm:"foreignKey:UserID" json:"user,omitempty"`
}

// AutoMigrate setups the DB schema
func AutoMigrate(db *gorm.DB) error {
	return db.AutoMigrate(
		&User{},
		&Match{},
		&MatchPlayer{},
	)
}
